-- Migration: replace_interview_questions
-- Replaces the seeded YPP instructor interview question bank with the May 2026 instructor
-- interview guide. Reuses existing slugs where the question intent matches so in-progress
-- review drafts keep their per-question response data; introduces 3 new slugs for the
-- situational scenarios that are new in the guide; deactivates 7 legacy slugs that no
-- longer appear in the guide so they disappear from the live runner without losing
-- historical responses (FK on InstructorInterviewQuestionResponse remains intact).
--
-- The new active set is 10 questions across 5 sections:
--   1. General Questions          (iqb_motivation, iqb_subject)
--   2. Teaching Ability           (iqb_structure, iqb_teach [must-ask])
--   3. Experience                 (iqb_experience)
--   4. Time Commitment / Priority (iqb_commitment)
--   5. Situational Questions      (iqb_situational_cursing, iqb_parent,
--                                  iqb_situational_retention, iqb_situational_knowledge_gap)

-- Replace / insert active questions.
INSERT INTO "InstructorInterviewQuestionBank" (
  "id",
  "slug",
  "prompt",
  "helperText",
  "followUpPrompt",
  "topic",
  "competency",
  "whyItMatters",
  "interviewerGuidance",
  "listenFor",
  "suggestedFollowUps",
  "strongSignals",
  "concernSignals",
  "notePrompts",
  "sortOrder",
  "isActive",
  "isMustAsk",
  "createdAt",
  "updatedAt"
)
VALUES
  (
    'iqb_motivation',
    'motivation_for_applying',
    'How did you hear about YPP, and what made you want to apply to teach?',
    'Open the interview. Lets the candidate warm up while signalling whether their motivation is student-centered or self-serving.',
    'What do you hope to get out of teaching at YPP?',
    'General Questions',
    'Authentic motivation',
    'Whether they actually care about teaching kids, or are mostly looking for a resume boost.',
    'Only ask the follow-up if the original answer is vague. Listen for a specific story or person, not a polished pitch.',
    'A clear, specific reason for applying. Concrete student-impact language. Personal anecdote behind the interest.',
    '["What do you hope to get out of teaching at YPP?"]'::jsonb,
    '["Talks about students and the teaching itself, not personal gain","Heard about YPP from someone they trust and wants to do it themselves","Has a clear, specific reason (e.g. wanted this kind of class as a kid)"]'::jsonb,
    '["ANYTHING about resume value or college apps","Vague answers like ''I just love helping people'' with no concrete anecdote","Cannot name why YPP specifically (vs. any other tutoring program)"]'::jsonb,
    '["Why YPP specifically","Student impact they named","Personal anecdote","Any resume/college motive"]'::jsonb,
    1,
    true,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_subject',
    'passion_for_subject',
    'What topic do you want to teach, and why?',
    'Tests whether their topic choice is a real passion or a random pick.',
    'When did your love for this subject really start, and is there any specific reason?',
    'General Questions',
    'Passion and depth of subject',
    'Is this a real passion, or did they pick a random topic that sounded interesting? We want the actual backstory.',
    'Push for a specific origin story. Strong candidates volunteer detail; weak ones can''t locate a moment of curiosity.',
    'A real story (often unprompted), specific anecdotes, and breadth/depth of subject knowledge.',
    '["When did your love for this subject really start, and is there any specific reason?"]'::jsonb,
    '["Tells a passion story without being asked","Knows specific, slightly unusual things about the topic","Naturally shows breadth and depth of knowledge"]'::jsonb,
    '["''I''ve always just liked it'' with no follow-up detail","Cannot say why or when they got into the topic","Sounds like they picked it because it was different, not because they actually like it"]'::jsonb,
    '["Backstory of the passion","Subject depth signals","Specific examples they cited","Authenticity"]'::jsonb,
    2,
    true,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_structure',
    'class_structure',
    'Walk me through your class structure. In 60 seconds, explain the outline that you gave me.',
    'Forces them to summarize their plan tightly. Reveals how much they''ve actually thought it through.',
    'What is the goal of your class? What is the end goal — a project, test, symposium, or something else?',
    'Teaching Ability',
    'Curriculum readiness',
    'Have they actually thought this through, and to what level? Do they understand what is doable with kids? This tests their professionalism.',
    'Time them softly to 60 seconds. Ask the follow-up only if the outline lacks an end-goal or feels invented on the spot.',
    'A clear arc from topic A to topic B. Genuine engagement with the content. A foreward thinker who anticipates what students need.',
    '["What is the goal of your class — what is the end goal (project, test, symposium, etc.)?"]'::jsonb,
    '["Clear arc with a beginning, middle, and end","Speaks with passion, not just reciting words","Anticipates where students will get stuck and what materials they will need (foreward thinker)"]'::jsonb,
    '["''I''ll just teach them about X'' with no plan whatsoever","''I''ll lecture for 45 minutes''","Plan is clearly being invented on the spot, no deep thought"]'::jsonb,
    '["Arc and pacing","End-goal clarity","Engagement plan","Signals of forethought (or lack of)"]'::jsonb,
    3,
    true,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_teach',
    'teach_in_60_seconds',
    'Pick one topic from your class and explain it to me like I''m in 6th grade.',
    'A live teaching demo — the single most diagnostic moment in the interview.',
    'I''m confused. What would you do next to reexplain?',
    'Teaching Ability',
    'Teaching ability',
    'Are they actually a good teacher? THIS IS THE MOST IMPORTANT QUESTION TO ASK. So many people know stuff — not everyone can teach it.',
    'Let them teach. Then play a confused student and watch how they respond. Push them: ask if they have a way to check that you actually understood it (not just nodding along).',
    'Analogies, examples, and comparisons that make the concept land. Calm adjustment when you push back. A check-for-understanding move.',
    '["I''m confused. What would you do next to reexplain?","Do you have a way of checking if I''m just nodding along, or if I actually understood it?"]'::jsonb,
    '["Uses analogies, examples, or comparisons that actually clarify the concept","Adjusts on the fly when you ask a follow-up","Checks for understanding and keeps the explanation engaging"]'::jsonb,
    '["Recites a textbook definition","Talks down to you or makes you feel dumb for not knowing it (SUPER RED FLAG)","Their explanation leaves the concept less clear than before they started"]'::jsonb,
    '["Clarity of the explanation","Use of analogy / example","How they reacted to your confusion","Did they check for understanding?","Tone toward the ''student''"]'::jsonb,
    4,
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_experience',
    'prior_teaching_experience',
    'Do you have any prior teaching experience? If so, what was it, and what are some things that you learned from it?',
    'Optional context. Past experience is not required, but reveals self-awareness when present.',
    NULL,
    'Experience',
    'Teaching reflection',
    'Past teaching experience is NOT required — but if they have it, this can shed light on how they will interact with students and parents.',
    'No strict good/bad answers here. Reflect honestly in your notes. Listen for self-awareness about what worked and what didn''t.',
    'Honest reflection. Concrete examples. Awareness of what they''re still learning.',
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["Experience type and length","What they learned","How they describe past students","Self-awareness"]'::jsonb,
    5,
    true,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_commitment',
    'time_commitment',
    'What other extracurriculars and activities are you involved in?',
    'Tests realistic capacity and whether YPP can actually be a priority for them.',
    'How much time out of your schedule do these things take?',
    'Time Commitment / Priority',
    'Reliability and time commitment',
    'Two reasons we ask: (1) whether they could potentially take on a section of another class if there are excess sign-ups, and (2) whether YPP is a doable priority for them.',
    'Walk through the follow-ups in order. The conflict and prioritization questions are where the real signal lives.',
    'Honest accounting of time. A specific plan for what happens when commitments conflict. Confident prioritization of YPP.',
    '["How much time out of your schedule do these things take?","Have you ever had problems with time management in the past, and how did you deal with it?","What would your approach be if another activity or obligation conflicted with a scheduled YPP session?","How confident are you that you can consistently prioritize your YPP teaching responsibilities, even during busy periods?"]'::jsonb,
    '["Names real time constraints honestly","Has handled time-management problems before and learned from it","Treats YPP as a serious commitment, not a side activity","Has bandwidth to potentially take on a second section"]'::jsonb,
    '["Schedule is already full with no slack","Has unresolved time-management problems","Treats other commitments as automatically winning over YPP","No realistic plan for conflicts"]'::jsonb,
    '["Other commitments","Real available hours per week","Conflict-handling plan","Priority-of-YPP signal","Capacity for a 2nd section"]'::jsonb,
    6,
    true,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_situational_cursing',
    'situational_cursing_student',
    'A student is dropping curse words left and right during your class, and it is preventing other students from being able to learn. How would you deal with this problem child?',
    'Situational test of classroom management and where they place responsibility.',
    NULL,
    'Situational Questions',
    'Classroom management',
    'Are they introspective about their own teaching, or do they default to blaming the student? Are they mature about behavior issues?',
    'Listen for the direction of their thinking. ''Reach out and make sure they know when classes are'' is OK and is not blame. ''Dismiss / kick out the student'' is a red flag. Reviewing curriculum, talking privately, and adjusting engagement are all in the right direction.',
    'Reflection on their own classroom dynamics. Private, calm intervention with the student. Escalation only after they''ve tried to solve it themselves.',
    '[]'::jsonb,
    '["Curious about why the behavior is happening before reacting","Talks to the student privately first","Adjusts the class engagement, not just discipline","Loops in chapter lead or parent only after attempting to solve directly"]'::jsonb,
    '["First instinct is to dismiss or remove the student","Blames the student without examining their own classroom dynamics","Public discipline that humiliates the student"]'::jsonb,
    '["Does the answer reflect on their own teaching first?","Private vs. public response","When they''d escalate","Tone toward the student"]'::jsonb,
    7,
    true,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_parent',
    'parent_scenario',
    'You receive an angry email from a parent claiming that you are not giving due attention to their child. First, how would you respond to this parent? Second, how would you change your behavior to seem more accommodating?',
    'Tests parent communication, ownership, and willingness to adjust behavior.',
    NULL,
    'Situational Questions',
    'Parent communication',
    'Are they introspective and accountable, or defensive? Do they treat the parent''s concern as valid information about their teaching?',
    'Two-part question — make sure they answer both. Listen for ownership without grovelling, and a concrete behavior change.',
    'A calm acknowledgment of the parent''s concern, a concrete next step, and a specific change to their own behavior.',
    '[]'::jsonb,
    '["Acknowledges the parent''s concern without arguing","Reflects on what the student may have actually experienced","Proposes specific behavior changes (more check-ins, slower pacing, named follow-ups)","Plans to document the conversation and follow up promptly"]'::jsonb,
    '["Defensive or dismissive of the parent''s email","Blames the student or the parent for the perception","Vague promise to ''do better'' with no concrete change","Suggests the parent is overreacting"]'::jsonb,
    '["Tone of the response","Did they propose a real behavior change?","Ownership vs. defensiveness","Follow-up plan"]'::jsonb,
    8,
    true,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_situational_retention',
    'situational_retention_drop',
    'You started out with ten students. The next class only 5 return, and the class after that you only have 2 students left. Students are dropping out of your class like flies — what steps do you take to fix your class retention rates?',
    'Tests whether they treat retention as a teacher problem first, not a student problem.',
    NULL,
    'Situational Questions',
    'Class engagement / retention',
    'Do they view the success of a class as a function of the teacher, or do they blame the students? Will they actually diagnose before they change things?',
    'Listen for diagnosis-before-action. The strongest answers ask students or parents what isn''t working before re-planning the class.',
    'Self-reflection on what made students leave. A diagnosis step (talk to students/parents). A concrete change in the next class.',
    '[]'::jsonb,
    '["Treats retention as a teacher problem first, not a student one","Plans to ask students/parents what isn''t working","Reviews their curriculum, pacing, and engagement strategy","Makes a concrete change in the next class"]'::jsonb,
    '["Blames students for being unmotivated or lazy","Says ''I''ll just keep teaching what I planned''","No diagnosis step before changing things","Suggests dismissing or replacing the remaining students"]'::jsonb,
    '["Where they place responsibility","Diagnosis plan","Concrete change for the next class","Tone toward the students who left"]'::jsonb,
    9,
    true,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_situational_knowledge_gap',
    'situational_knowledge_gap',
    'It is your first class of teaching. Half the students seem to already know everything you are talking about, and the other half are learning this for the first time. What do you do to amend this knowledge gap with students?',
    'Tests differentiation skill and whether they can adapt instruction for mixed levels.',
    NULL,
    'Situational Questions',
    'Differentiated instruction',
    'Can they adjust instruction for students at different levels without lowering the ceiling or losing the floor?',
    'Listen for a real differentiation plan. ''Teach to the middle'' is a yellow flag. The strongest answers split work, use stretch tasks, and use peer-teaching.',
    'A specific plan for both groups. Use of stretch tasks, peer teaching, or scaffolding. Awareness that this is a teacher problem to solve.',
    '[]'::jsonb,
    '["Splits work — stretch tasks for advanced students, scaffolding for beginners","Uses peer teaching (have one explain to the other)","Adapts pacing without lowering the ceiling","Surveys / checks understanding before pushing forward"]'::jsonb,
    '["Teaches to the middle and hopes for the best","Implies struggling students should leave or catch up on their own","No real plan for differentiation","Blames the level mix instead of solving for it"]'::jsonb,
    '["Plan for advanced students","Plan for beginners","Differentiation strategy","Tone toward the lower-level students"]'::jsonb,
    10,
    true,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("slug") DO UPDATE SET
  "prompt" = EXCLUDED."prompt",
  "helperText" = EXCLUDED."helperText",
  "followUpPrompt" = EXCLUDED."followUpPrompt",
  "topic" = EXCLUDED."topic",
  "competency" = EXCLUDED."competency",
  "whyItMatters" = EXCLUDED."whyItMatters",
  "interviewerGuidance" = EXCLUDED."interviewerGuidance",
  "listenFor" = EXCLUDED."listenFor",
  "suggestedFollowUps" = EXCLUDED."suggestedFollowUps",
  "strongSignals" = EXCLUDED."strongSignals",
  "concernSignals" = EXCLUDED."concernSignals",
  "notePrompts" = EXCLUDED."notePrompts",
  "sortOrder" = EXCLUDED."sortOrder",
  "isActive" = EXCLUDED."isActive",
  "isMustAsk" = EXCLUDED."isMustAsk",
  "updatedAt" = CURRENT_TIMESTAMP;

-- Deactivate the 7 legacy slugs that no longer appear in the May 2026 guide.
-- Setting isActive = false hides them from the live runner without deleting the rows,
-- so historical InstructorInterviewQuestionResponse rows still resolve their question text.
UPDATE "InstructorInterviewQuestionBank"
SET "isActive" = false,
    "updatedAt" = CURRENT_TIMESTAMP
WHERE "slug" IN (
  'subject_depth',
  'curriculum_adaptation',
  'student_scenario',
  'professionalism_followthrough',
  'community_fit',
  'coachability_feedback',
  'candidate_questions'
)
AND "isActive" = true;
