import Link from "next/link";

const studentNav = [["/student", "Home"], ["/student/learning", "My Learning"], ["/student/explore", "Explore"], ["/student/work", "My Work"], ["/student/support", "Support"], ["/student/profile", "Profile"]];
const parentNav = [["/parent", "Home"], ["/parent/students", "My Students"], ["/parent/schedule", "Schedule"], ["/parent/explore", "Explore"], ["/parent/forms", "Forms"], ["/parent/support", "Support"], ["/parent/settings", "Family Settings"]];

function Shell({ title, nav, children }: { title: string; nav: string[][]; children: React.ReactNode }) {
  return <main className="min-h-screen bg-[#fbfaf8] text-slate-950"><a href="#portal-content" className="sr-only focus:not-sr-only focus:absolute focus:m-4 focus:rounded-md focus:bg-white focus:p-3">Skip to portal content</a><div className="mx-auto flex w-full max-w-6xl flex-col gap-6 px-4 py-5 sm:px-6 lg:px-8"><header className="rounded-3xl border border-stone-200 bg-white p-3 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><Link href={nav[0][0]} className="text-lg font-semibold tracking-tight">{title}</Link><nav aria-label={`${title} navigation`} className="flex gap-1 overflow-x-auto pb-1"><ul className="flex gap-1">{nav.map(([href,label])=><li key={href}><Link href={href} className="whitespace-nowrap rounded-full px-3 py-2 text-sm font-medium text-slate-700 outline-none transition-colors hover:bg-violet-50 focus-visible:ring-2 focus-visible:ring-violet-500 motion-reduce:transition-none">{label}</Link></li>)}</ul></nav></div></header><section id="portal-content" className="space-y-6">{children}</section></div></main>;
}
export function StudentPortalShell({ children }: { children: React.ReactNode }) { return <Shell title="YPP Student Portal" nav={studentNav}>{children}</Shell>; }
export function ParentPortalShell({ children }: { children: React.ReactNode }) { return <Shell title="YPP Parent Portal" nav={parentNav}>{children}</Shell>; }
export function EmptyState({ title, body, action }: { title: string; body: string; action?: React.ReactNode }) { return <div className="rounded-2xl border border-dashed border-stone-300 bg-white p-6"><h2 className="text-lg font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{body}</p>{action ? <div className="mt-4">{action}</div> : null}</div>; }
export function GuardianStudentSwitcher({ students, currentStudentId }: { students: { studentUserId: string; studentUser?: { name: string } }[]; currentStudentId?: string }) { if (students.length <= 1) return null; return <nav aria-label="Switch student" className="rounded-2xl border bg-white p-3"><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">Viewing student</p><div className="flex flex-wrap gap-2">{students.map((s)=><Link key={s.studentUserId} href={`/parent/students/${s.studentUserId}`} className={`rounded-full px-3 py-2 text-sm ${currentStudentId===s.studentUserId?"bg-violet-700 text-white":"bg-stone-100 text-slate-800"}`}>{s.studentUser?.name ?? "Student"}</Link>)}</div></nav>; }
