import type { NavGroup, NavLink, NavRole } from "@/lib/navigation/types";

type CatalogInput = Omit<NavLink, "group" | "priority" | "coreEligible"> & {
  coreEligible?: boolean;
};

const INSTRUCTOR_ROLES: NavRole[] = ["INSTRUCTOR", "ADMIN", "CHAPTER_PRESIDENT"];
const INSTRUCTOR_AND_APPLICANT_ROLES: NavRole[] = ["APPLICANT", "INSTRUCTOR", "ADMIN", "CHAPTER_PRESIDENT"];
const MENTOR_ROLES: NavRole[] = ["MENTOR", "CHAPTER_PRESIDENT", "ADMIN"];
const MY_PROGRAM_ROLES: NavRole[] = ["STUDENT", "INSTRUCTOR", "CHAPTER_PRESIDENT", "ADMIN", "STAFF"];
const APPLICANT_ROLES: NavRole[] = ["APPLICANT", "STUDENT", "INSTRUCTOR", "STAFF", "ADMIN"];
// Like APPLICANT_ROLES but excludes APPLICANT — used for the broader
// "My Applications" tracker, since applicants already have "My Application"
// (singular) pointing at /application-status and the plural view would
// redirect right back for them.
const APPLICANT_ROLES_EXCLUDING_APPLICANT: NavRole[] = ["STUDENT", "INSTRUCTOR", "STAFF", "ADMIN"];
const INTERVIEW_ROLES: NavRole[] = ["INSTRUCTOR", "STAFF", "ADMIN", "CHAPTER_PRESIDENT"];
const ADMIN_ONLY: NavRole[] = ["ADMIN"];
const HIRING_CHAIR_ADMIN_ROLES: NavRole[] = ["ADMIN", "HIRING_CHAIR"];
const PARENT_ONLY: NavRole[] = ["PARENT"];
const STUDENT_ONLY: NavRole[] = ["STUDENT"];
const CHAPTER_PRESIDENT_ONLY: NavRole[] = ["CHAPTER_PRESIDENT"];
const INSTRUCTOR_APPLICANT_ONLY: NavRole[] = ["APPLICANT"];

function groupLinks(group: NavGroup, basePriority: number, links: CatalogInput[]): NavLink[] {
  return links.map((link, index) => ({
    ...link,
    group,
    priority: basePriority + index,
    coreEligible: link.coreEligible ?? true,
  }));
}

export const NAV_CATALOG: NavLink[] = [
  ...groupLinks("Start Here", 50, [
    {
      href: "/application-status",
      label: "My Application",
      icon: "📋",
      roles: INSTRUCTOR_APPLICANT_ONLY,
      dashboardDescription: "Track the status of your instructor application.",
      dashboardPriority: 1,
      coreEligible: true,
    },
    {
      href: "/my-interview",
      label: "My Interview",
      icon: "🎤",
      roles: INSTRUCTOR_APPLICANT_ONLY,
      dashboardDescription: "Schedule and track your application interview.",
      dashboardPriority: 2,
      coreEligible: true,
    },
    {
      href: "/instructor-onboarding",
      label: "Instructor Onboarding",
      icon: "🧭",
      roles: INSTRUCTOR_ROLES,
      searchAliases: ["Onboarding Guide", "Instructor Guide", "Portal Walkthrough"],
      dashboardDescription: "Read the instructor onboarding guide and portal walkthrough.",
      dashboardPriority: 3,
      coreEligible: true,
    },
  ]),

  ...groupLinks("Family", 100, [
    {
      href: "/parent",
      label: "Parent Portal",
      icon: "🏠",
      roles: PARENT_ONLY,
      dashboardDescription: "View your linked students and progress signals.",
      dashboardPriority: 3,
    },
    {
      href: "/parent/student-intake/new",
      label: "Start Student Journey",
      icon: "🧭",
      roles: PARENT_ONLY,
      dashboardDescription: "Begin a new parent-led student intake journey.",
      dashboardPriority: 4,
    },
    {
      href: "/parent/resources",
      label: "Resources",
      icon: "📚",
      roles: PARENT_ONLY,
      dashboardDescription: "Access parent guidance and support resources.",
      dashboardPriority: 12,
    },
    {
      href: "/parent/connect",
      label: "Connect Student",
      icon: "🔗",
      roles: PARENT_ONLY,
      dashboardDescription: "Connect and manage student link requests.",
      dashboardPriority: 11,
    },
  ]),

  ...groupLinks("Start Here", 200, [
    {
      href: "/",
      label: "Home",
      icon: "▣",
      dashboardDescription: "Your primary-role command center with queues and next actions.",
      dashboardPriority: 1,
    },
    {
      href: "/admin",
      label: "Administration",
      icon: "🛠",
      roles: ADMIN_ONLY,
      dashboardDescription:
        "Open the admin hub for hiring, programs, content, analytics, and platform operations.",
      dashboardPriority: 2,
      coreEligible: true,
    },
    {
      href: "/interviews",
      label: "Interviews",
      icon: "🎤",
      roles: INTERVIEW_ROLES,
      coreEligible: false,
      dashboardDescription: "Run interview scheduling, confirmations, and outcomes in one command center.",
      dashboardPriority: 7,
      dashboardBadgeKey: "interview_queue",
    },
    {
      href: "/scheduling",
      label: "Scheduling Hub",
      icon: "🗓",
      roles: ["APPLICANT", "STUDENT", "INSTRUCTOR", "STAFF", "ADMIN", "CHAPTER_PRESIDENT", "MENTOR"] as NavRole[],
      dashboardDescription: "See interviews, mentorship, and college-advisor scheduling work in one place.",
      dashboardPriority: 8,
    },
    {
      href: "/announcements",
      label: "Updates",
      icon: "📢",
      dashboardDescription: "Read chapter and platform updates.",
      dashboardPriority: 25,
    },
    {
      href: "/messages",
      label: "Messages",
      icon: "✉",
      roles: ["STUDENT", "INSTRUCTOR", "ADMIN", "CHAPTER_PRESIDENT", "MENTOR", "STAFF", "APPLICANT", "PARENT"] as NavRole[],
      badgeKey: "messages",
      dashboardBadgeKey: "unread_messages",
      dashboardDescription: "Open direct, parent, and interview conversations in one shared inbox.",
      dashboardPriority: 9,
    },
    { href: "/feedback/anonymous", label: "Anonymous Feedback", icon: "💬" },
  ]),

  ...groupLinks("Learning", 300, [
    {
      href: "/my-chapter",
      label: "My Chapter",
      icon: "🏠",
      roles: STUDENT_ONLY,
      dashboardDescription: "Open your chapter-first pathway hub with local runs, next steps, and fallback options.",
      dashboardPriority: 4,
    },
    { href: "/pathways", label: "Pathways", icon: "🗺" },
    { href: "/curriculum", label: "Curriculum Catalog", icon: "📖" },
    {
      href: "/my-classes",
      label: "My Classes",
      icon: "🎓",
      roles: STUDENT_ONLY,
      searchAliases: ["My Courses"],
    },
    {
      href: "/my-classes/assignments",
      label: "Assignments",
      icon: "📝",
      roles: STUDENT_ONLY,
      dashboardDescription: "Due work from all your classes in one list.",
      dashboardPriority: 5,
    },
    { href: "/curriculum/schedule", label: "My Schedule", icon: "📅", roles: STUDENT_ONLY },
    {
      href: "/curriculum/recommended",
      label: "Recommended Classes",
      icon: "⭐",
      roles: STUDENT_ONLY,
      searchAliases: ["Recommended", "Recommended Courses"],
    },
    { href: "/learn/modules", label: "Modules", icon: "📦", roles: STUDENT_ONLY },
    { href: "/learn/workshops", label: "Workshops", icon: "🔧", roles: STUDENT_ONLY },
    { href: "/learn/style-quiz", label: "Style Quiz", icon: "🧩", roles: STUDENT_ONLY },
    { href: "/learn/challenges", label: "Challenge Learning", icon: "⚡", roles: STUDENT_ONLY },
    { href: "/learn/practice", label: "Practice Log", icon: "🏋", roles: STUDENT_ONLY },
    { href: "/learn/progress", label: "My Progress", icon: "📈", roles: STUDENT_ONLY },
    {
      href: "/student-training",
      label: "Training Academy",
      icon: "🏫",
      roles: STUDENT_ONLY,
      searchAliases: ["Training", "Student Training"],
      dashboardDescription: "Complete assigned modules, checkpoints, quizzes, and evidence submissions.",
      dashboardPriority: 6,
    },
    { href: "/programs", label: "Programs Catalog", icon: "🎯" },
  ]),

  ...groupLinks("Progress", 400, [
    {
      href: "/goals",
      label: "My Goals",
      icon: "🎯",
      dashboardDescription: "Track progress against your active goals.",
      dashboardPriority: 12,
    },
    { href: "/analytics", label: "Analytics", icon: "📊", roles: STUDENT_ONLY },
    { href: "/learn/path-generator", label: "Learning Paths", icon: "🧭", roles: STUDENT_ONLY },
    { href: "/pathways/progress", label: "Pathway Progress", icon: "📈", roles: STUDENT_ONLY },
    {
      href: "/projects/tracker",
      label: "Project Tracker",
      icon: "📝",
      roles: STUDENT_ONLY,
      searchAliases: ["My Projects"],
    },
    {
      href: "/activities",
      label: "Activities",
      icon: "🧭",
      roles: STUDENT_ONLY,
      searchAliases: ["Activity Hub"],
      dashboardDescription: "Choose your next challenge, try-it, incubator, or project action.",
      dashboardPriority: 7,
    },
    { href: "/motivation", label: "Motivation", icon: "🔥", roles: STUDENT_ONLY },
    { href: "/reflections/streaks", label: "Reflection Streaks", icon: "🔗", roles: STUDENT_ONLY },
    {
      href: "/reflection",
      label: "Monthly Reflection",
      icon: "📝",
      roles: ["INSTRUCTOR", "CHAPTER_PRESIDENT"],
      hideForPrimaryRoles: ["ADMIN"],
    },
    {
      href: "/admin/reflections",
      label: "Reflection reviews",
      icon: "💭",
      roles: ADMIN_ONLY,
      dashboardDescription: "Review staff and instructor self-reflection submissions.",
      dashboardPriority: 9,
    },
    {
      href: "/instructor-training",
      label: "Instructor Training",
      icon: "🎓",
      searchAliases: ["Training Academy", "Training"],
      roles: INSTRUCTOR_ROLES,
      dashboardDescription: "Complete all required academy modules to unlock offering approval.",
      dashboardPriority: 4,
      dashboardBadgeKey: "training_incomplete",
    },
    {
      href: "/instructor/lesson-design-studio",
      label: "Lesson Design Studio",
      icon: "🎨",
      roles: INSTRUCTOR_AND_APPLICANT_ROLES,
      dashboardDescription: "Continue your studio journey by browsing examples, completing the guided tour, and building a full curriculum in one studio.",
      dashboardPriority: 17,
    },
    {
      // Surfaced only for INSTRUCTOR-role users (resolveNavModel further
      // restricts to subtype = SUMMER_WORKSHOP, so APPLICANT and full
      // instructors don't see this in their sidebar).
      href: "/instructor/workshop-design-studio",
      label: "Workshop Design Studio",
      icon: "🛠️",
      roles: INSTRUCTOR_ROLES,
      requiresSummerWorkshopSubtype: true,
      dashboardDescription: "Propose the focused workshop you'll lead at camp — design your own or pick from the approved library.",
      dashboardPriority: 17,
      searchAliases: ["Workshop Proposal", "Workshop Outline"],
    },
    {
      href: "/lesson-plans",
      label: "Lesson Plans",
      icon: "📋",
      roles: INSTRUCTOR_ROLES,
      featureKey: "INSTRUCTOR_TEACHING_TOOLS",
      dashboardDescription: "Draft and refine lesson plans for upcoming sessions.",
      dashboardPriority: 18,
    },
    {
      href: "/instructor/lesson-plans/templates",
      label: "Plan Templates",
      icon: "📄",
      roles: INSTRUCTOR_ROLES,
      featureKey: "INSTRUCTOR_TEACHING_TOOLS",
    },
    {
      href: "/instructor/workspace",
      label: "Instructor Workspace",
      icon: "🧩",
      roles: INSTRUCTOR_ROLES,
      featureKey: "INSTRUCTOR_TEACHING_TOOLS",
      dashboardDescription: "Plan curricula, lesson plans, offerings, and readiness in one workspace.",
      dashboardPriority: 2,
    },
    {
      href: "/instructor/curriculum-builder",
      label: "Curriculum Builder",
      icon: "🛠",
      roles: INSTRUCTOR_ROLES,
      featureKey: "INSTRUCTOR_TEACHING_TOOLS",
    },
    {
      href: "/instructor/class-settings",
      label: "Class Settings",
      icon: "⚙",
      roles: INSTRUCTOR_ROLES,
      featureKey: "INSTRUCTOR_TEACHING_TOOLS",
      dashboardDescription: "Manage class offerings, schedules, and publish settings.",
      dashboardPriority: 3,
    },
    {
      href: "/instructor/peer-observation",
      label: "Peer Observation",
      icon: "👁",
      roles: INSTRUCTOR_ROLES,
      featureKey: "INSTRUCTOR_TEACHING_TOOLS",
    },
    {
      href: "/instructor/mentee-health",
      label: "Mentee Health",
      icon: "💚",
      roles: INSTRUCTOR_ROLES,
    },
  ]),

  ...groupLinks("Challenges", 500, [
    { href: "/challenges", label: "Challenges", icon: "⚡" },
    { href: "/challenges/daily", label: "Daily Challenges", icon: "🌟" },
    { href: "/challenges/weekly", label: "Weekly Prompts", icon: "📝" },
    { href: "/challenges/streaks", label: "Streaks", icon: "🔥" },
    { href: "/challenges/nominate", label: "Nominate Challenge", icon: "👍" },
    { href: "/challenges/passport", label: "Passion Passport", icon: "📘" },
    { href: "/competitions", label: "Competitions", icon: "🏆" },
    { href: "/competitions/checklist", label: "Competition Checklist", icon: "☑" },
    { href: "/showcases", label: "Seasonal Events", icon: "🎉" },
    { href: "/leaderboards", label: "Leaderboards", icon: "📊" },
    { href: "/rewards", label: "Rewards", icon: "🎁" },
    { href: "/achievements/badges", label: "Badge Gallery", icon: "🏅" },
    { href: "/student-of-month", label: "Student of the Month", icon: "⭐" },
    { href: "/wall-of-fame", label: "Wall of Fame", icon: "🏛" },
  ]),

  ...groupLinks("Projects", 600, [
    { href: "/incubator", label: "Project Incubator", icon: "🚀" },
    { href: "/incubator/apply", label: "Apply", icon: "📩" },
    { href: "/mentor/incubator", label: "Project Mentoring", icon: "🧭", roles: MENTOR_ROLES },
    { href: "/showcase", label: "Student Showcase", icon: "🎨" },
    { href: "/showcase/submit", label: "Share Your Work", icon: "📤" },
  ]),

  ...groupLinks("Opportunities", 700, [
    { href: "/internships", label: "Opportunities", icon: "💼" },
    { href: "/service-projects", label: "Service Projects", icon: "🤝" },
    { href: "/resource-exchange", label: "Resource Exchange", icon: "🔄" },
    { href: "/portfolio/templates", label: "Portfolio Templates", icon: "📂" },
    { href: "/events/map", label: "Chapter Events Map", icon: "🗺" },
    {
      href: "/positions",
      label: "Open Positions",
      icon: "📌",
      roles: APPLICANT_ROLES,
      searchAliases: ["Leadership/Instructor Openings"],
      dashboardDescription: "Browse active hiring openings and role details.",
      dashboardPriority: 14,
    },
    {
      href: "/applications",
      label: "My Applications",
      icon: "📨",
      roles: APPLICANT_ROLES_EXCLUDING_APPLICANT,
      dashboardDescription: "Track your submitted applications and interview status.",
      dashboardPriority: 8,
      dashboardBadgeKey: "active_applications",
    },
    {
      href: "/instructor/certification-pathway",
      label: "Cert Pathway",
      icon: "📜",
      roles: ["INSTRUCTOR", "ADMIN"],
    },
  ]),

  ...groupLinks("People & Support", 800, [
    {
      href: "/actions",
      label: "My Actions",
      icon: "✅",
      // My Actions is per-record guarded server-side and can be used by any
      // portal user who is assigned as Lead, Executing, or Input.
      roles: [
        "ADMIN",
        "STAFF",
        "CHAPTER_PRESIDENT",
        "HIRING_CHAIR",
        "INSTRUCTOR",
        "MENTOR",
        "STUDENT",
        "PARENT",
        "APPLICANT",
      ] as NavRole[],
      requiresActionTracker: true,
      searchAliases: ["Action Items", "Action Tracker", "My Action Items"],
      dashboardDescription: "Everything you lead, are executing, or owe input on — sorted by deadline.",
      dashboardPriority: 5,
    },
    {
      href: "/actions/command-center",
      label: "Command Center",
      icon: "🎛️",
      // Officer-tier and above only (mirrors requireOfficer()).
      roles: ["ADMIN", "STAFF", "CHAPTER_PRESIDENT", "HIRING_CHAIR"] as NavRole[],
      requiresActionTracker: true,
      searchAliases: [
        "People Strategy",
        "Weekly Pulse",
        "Attention Queue",
        "Momentum",
        "Leadership Command Center",
        "People Strategy OS",
      ],
      dashboardDescription:
        "This week's pulse, the attention queue, people momentum, and wins — the People Strategy command center.",
      dashboardPriority: 6,
    },
    {
      href: "/actions/all",
      label: "All Actions",
      icon: "🗂️",
      // Officer-tier and above only (mirrors requireOfficer()).
      roles: ["ADMIN", "STAFF", "CHAPTER_PRESIDENT", "HIRING_CHAIR"] as NavRole[],
      requiresActionTracker: true,
      searchAliases: [
        "Action Tracker",
        "Leadership Actions",
        "All Action Items",
        "Leadership Action Center",
        "Officer Operations",
        "Weekly Action Tracker",
      ],
      dashboardDescription: "Every leadership action item, grouped by department.",
      dashboardPriority: 5,
    },
    {
      href: "/actions/meetings",
      label: "Officer Meetings",
      icon: "📅",
      // Officer-tier and above only (mirrors requireOfficer()).
      roles: ["ADMIN", "STAFF", "CHAPTER_PRESIDENT", "HIRING_CHAIR"] as NavRole[],
      requiresActionTracker: true,
      searchAliases: ["Meetings", "Officer Meeting", "Agenda"],
      dashboardDescription: "Schedule officer meetings, link action items, and capture notes.",
      dashboardPriority: 5,
    },
    {
      href: "/leadership-pathway",
      label: "Leadership Pathway",
      icon: "🪜",
      roles: ["INSTRUCTOR", "MENTOR", "CHAPTER_PRESIDENT", "ADMIN", "STAFF"] as NavRole[],
      searchAliases: [
        "Role",
        "Roles",
        "Senior Instructor",
        "Lead Instructor",
        "Promotion",
        "Career",
        "Growth Pathway",
        "My Mentor",
      ],
      dashboardDescription:
        "See where you fit on the YPP instructor pathway and who's mentoring you.",
      dashboardPriority: 4,
    },
    {
      href: "/mentorship",
      label: "Mentorship",
      icon: "🤝",
      roles: MENTOR_ROLES,
      searchAliases: ["Support Hub", "Mentor Workspace"],
      dashboardDescription: "Open the mentor and operator workspace for circles, queues, and support operations.",
      dashboardPriority: 16,
    },
    {
      href: "/my-mentor",
      label: "My Mentor",
      icon: "🤝",
      roles: ["INSTRUCTOR", "CHAPTER_PRESIDENT", "ADMIN", "STAFF"] as NavRole[],
      searchAliases: ["My Mentorship", "Mentorship", "Mentor"],
      dashboardDescription: "See your mentor, goals, resources, progress, reflection, and next steps.",
      dashboardPriority: 4,
    },
    {
      href: "/mentorship/mentees",
      label: "My Mentees",
      icon: "👥",
      roles: MENTOR_ROLES,
      dashboardDescription: "Review mentee progress and follow-up needs.",
      dashboardPriority: 5,
      dashboardBadgeKey: "active_mentees",
    },
    {
      href: "/mentorship/reviews",
      label: "Review Inbox",
      icon: "✅",
      roles: MENTOR_ROLES,
      searchAliases: ["Chair Queue", "Review Approvals", "Monthly Review Inbox"],
      dashboardDescription: "Approve or return monthly goal reviews waiting on chair action.",
      dashboardPriority: 6,
    },
    {
      href: "/mentorship/schedule",
      label: "Mentor Schedule",
      icon: "📅",
      roles: MENTOR_ROLES,
      dashboardDescription: "Manage availability and confirm session requests from your mentees.",
      dashboardPriority: 8,
    },
    {
      href: "/mentorship/feedback",
      label: "Feedback Portal",
      icon: "💬",
      roles: MENTOR_ROLES,
      searchAliases: ["Mentee Feedback", "Feedback Requests", "Review Work"],
      dashboardDescription: "Respond to private feedback requests on mentee projects, drafts, and work samples.",
      dashboardPriority: 9,
    },
    {
      href: "/mentorship/ask",
      label: "Ask a Mentor",
      icon: "❓",
      roles: MENTOR_ROLES,
      searchAliases: ["Mentor Commons", "Mentor Q&A", "Answer Questions"],
      dashboardDescription: "Answer public questions and grow the shared mentor knowledge commons.",
      dashboardPriority: 10,
    },
    {
      href: "/mentorship/resources",
      label: "Mentor Resources",
      icon: "📚",
      roles: MENTOR_ROLES,
      searchAliases: ["Resource Commons", "Mentor Playbooks"],
      dashboardDescription: "Search and publish shared playbooks, templates, and resources from mentoring work.",
      dashboardPriority: 11,
    },
    // /mentorship/unlock-sections is intentionally not surfaced in top-level
    // nav -- it's a rare, contextual action accessed from a mentee's workspace.
    {
      href: "/my-program",
      label: "My Program",
      icon: "🎯",
      roles: MY_PROGRAM_ROLES,
      searchAliases: ["My Mentor", "Support Hub", "Program Hub"],
      dashboardDescription: "Open your support hub for reflections, action items, awards, rewards, and recognition.",
    },
    {
      href: "/my-program/gr",
      label: "My Goals",
      icon: "📋",
      roles: ["INSTRUCTOR", "CHAPTER_PRESIDENT", "ADMIN", "STAFF"] as NavRole[],
      featureKey: "GR_SYSTEM",
      searchAliases: ["My G&R", "Goals & Responsibilities"],
      dashboardDescription: "View your Goals & Responsibilities document, track progress, and update your plan of action.",
      dashboardPriority: 5,
    },
    // Removed from nav:
    //   /mentorship-program           -> redirects to /mentorship
    //   /mentorship-program/reviews   -> mentor surface duplicates the per-
    //                                    mentee "Write Review" CTA on the
    //                                    mentee detail page; mentee surface
    //                                    is the monthly self-reflection form
    //                                    accessed from the mentee dashboard.
    // /mentorship-program/chair removed from nav — it is a legacy redirect to
    // /mentorship/reviews, which already surfaces for ADMIN via MENTOR_ROLES.
    // Two "Chair Queue" entries created a duplicate visible label for admins.
    {
      href: "/mentorship/awards",
      label: "Awards",
      icon: "🏆",
      roles: ["MENTOR", "CHAPTER_PRESIDENT", "ADMIN"] as NavRole[],
      dashboardDescription: "Nominate mentees for Bronze, Silver, Gold, and Lifetime achievement awards.",
    },
    {
      href: "/my-mentor/awards",
      label: "My Awards",
      icon: "🏅",
      roles: ["INSTRUCTOR", "CHAPTER_PRESIDENT", "ADMIN", "STAFF"] as NavRole[],
      dashboardDescription: "View your achievement points, tier progress, and award nominations.",
    },
    {
      href: "/my-program/achievement-journey",
      label: "Achievement Journey",
      icon: "🏆",
      roles: ["INSTRUCTOR", "CHAPTER_PRESIDENT", "ADMIN", "STAFF"] as NavRole[],
      dashboardDescription: "Visualize your tier progress, earning velocity, and point history.",
    },
    {
      href: "/instructor-growth",
      label: "Instructor Growth",
      icon: "📈",
      roles: ["INSTRUCTOR", "CHAPTER_PRESIDENT", "ADMIN"] as NavRole[],
      dashboardDescription: "Track private instructor XP, tiers, badges, and semester momentum.",
      dashboardPriority: 7,
    },
    {
      href: "/instructor-growth/review",
      label: "Growth Review Board",
      icon: "🗂️",
      roles: ["MENTOR", "CHAPTER_PRESIDENT", "ADMIN"] as NavRole[],
      dashboardDescription: "Review pending instructor growth claims in mentor and leadership lanes.",
      dashboardPriority: 7,
    },
    {
      href: "/my-program/schedule",
      label: "Schedule Meeting",
      icon: "📅",
      roles: ["INSTRUCTOR", "CHAPTER_PRESIDENT", "ADMIN", "STAFF"] as NavRole[],
      dashboardDescription: "Request a meeting with your mentor or manage upcoming sessions.",
    },
    // Removed from nav:
    //   /mentorship-program/schedule  -> redirects to /mentorship/schedule
    //   /mentorship/calendar          -> redirects to /mentorship/schedule
    // The canonical "Mentor Schedule" entry sits above next to "My Mentees".
    {
      href: "/peer-recognition",
      label: "Peer Recognition",
      icon: "🎉",
      dashboardDescription: "Send kudos and celebrate your teammates' contributions.",
    },
    {
      href: "/my-program/certificate",
      label: "My Certificate",
      icon: "📜",
      roles: ["INSTRUCTOR", "CHAPTER_PRESIDENT", "ADMIN", "STAFF"] as NavRole[],
      dashboardDescription: "Download your achievement certificate and volunteer hours verification letter.",
    },
    {
      href: "/college-advisor/roadmap",
      label: "College Roadmap",
      icon: "🎓",
      roles: ["INSTRUCTOR", "CHAPTER_PRESIDENT", "ADMIN", "STAFF"] as NavRole[],
      dashboardDescription: "Follow your personalized college readiness journey from exploration to transition.",
    },
    {
      href: "/college-advisor/activities",
      label: "Activities Builder",
      icon: "📋",
      roles: ["INSTRUCTOR", "CHAPTER_PRESIDENT", "ADMIN", "STAFF"] as NavRole[],
      dashboardDescription: "Build your extracurricular portfolio and export in Common App format.",
    },
    {
      href: "/alumni-network",
      label: "Alumni Network",
      icon: "🤝",
      dashboardDescription: "Connect with YPP alumni, attend panel events, and send intro requests.",
    },
    { href: "/events", label: "Events & Prep", icon: "📅" },
    { href: "/calendar", label: "Calendar", icon: "🗓" },
    {
      href: "/office-hours",
      label: "Office Hours",
      icon: "🕒",
      dashboardDescription: "Host or book office hours support sessions.",
      dashboardPriority: 20,
    },
    { href: "/check-in", label: "Check-In", icon: "✔", roles: STUDENT_ONLY },
    {
      href: "/attendance",
      label: "Attendance",
      icon: "📋",
      roles: INSTRUCTOR_ROLES,
      dashboardDescription: "Record and review class attendance sessions.",
      dashboardPriority: 11,
    },
    {
      href: "/instructor/parent-feedback",
      label: "Parent Feedback",
      icon: "💬",
      roles: ["INSTRUCTOR", "CHAPTER_PRESIDENT"] as NavRole[],
      dashboardDescription: "View parent feedback and communications for your classes.",
      dashboardPriority: 13,
    },
  ]),

  ...groupLinks("Chapters", 900, [
    {
      href: "/chapter/hub",
      label: "Chapter Hub",
      icon: "🏘",
      dashboardDescription: "Open one page with every chapter tool and directory link.",
      dashboardPriority: 1,
      coreEligible: true,
      searchAliases: ["Chapter", "Chapter tools", "Chapter directory", "Members", "Channels", "Leaderboard"],
    },
    {
      href: "/chapters",
      label: "Find a Chapter",
      icon: "🔍",
      dashboardDescription: "Browse chapters and find a community near you.",
      dashboardPriority: 26,
    },
    {
      href: "/join-chapter",
      label: "Join a Chapter",
      icon: "🤝",
      dashboardDescription: "Pick a chapter to join and start your journey.",
      dashboardPriority: 25,
    },
    {
      href: "/chapter/apply",
      label: "Apply for CP",
      icon: "🗺",
      dashboardDescription: "Apply to become a chapter president and lead a YPP chapter.",
      dashboardPriority: 13,
    },
    {
      href: "/chapter",
      label: "Command Center",
      icon: "🧭",
      roles: CHAPTER_PRESIDENT_ONLY,
      dashboardDescription: "Run your chapter: health, action queues, members, and operations.",
      dashboardPriority: 1,
      searchAliases: ["Dashboard", "Chapter OS", "President Dashboard", "Overview"],
    },
    {
      href: "/chapter/president",
      label: "Chapter President",
      icon: "👑",
    },
    {
      href: "/chapter/calendar",
      label: "Chapter Calendar",
      icon: "🗓",
      roles: CHAPTER_PRESIDENT_ONLY,
      dashboardDescription: "Create chapter events, recurring series, and public calendar items.",
      dashboardPriority: 4,
    },
    {
      href: "/chapter/student-intake",
      label: "Student Intake",
      icon: "🧭",
      roles: ["CHAPTER_PRESIDENT", "ADMIN"] as NavRole[],
      dashboardDescription: "Review parent-led student journeys and launch early support plans.",
      dashboardPriority: 5,
    },
    {
      href: "/chapter/onboarding",
      label: "CP Onboarding",
      icon: "🎓",
      roles: CHAPTER_PRESIDENT_ONLY,
    },
    {
      href: "/chapter/recruiting",
      label: "Chapter Recruiting",
      icon: "🧑‍💼",
      roles: CHAPTER_PRESIDENT_ONLY,
      dashboardDescription: "Manage openings, candidates, interviews, and decisions.",
      dashboardPriority: 2,
      dashboardBadgeKey: "chapter_recruiting_queue",
    },
    {
      href: "/chapter/channels",
      label: "Chapter Channels",
      icon: "💬",
      dashboardDescription: "Discussion channels for your chapter community.",
      dashboardPriority: 22,
    },
    {
      href: "/chapter/updates",
      label: "Chapter Announcements",
      icon: "📢",
      roles: CHAPTER_PRESIDENT_ONLY,
      coreEligible: false,
      dashboardDescription: "Post announcements and updates to your chapter.",
      dashboardPriority: 22,
      searchAliases: ["Announcements", "Chapter Updates", "Post Update"],
    },
    {
      href: "/chapter/members",
      label: "Chapter Members",
      icon: "👥",
      dashboardDescription: "View and search your chapter's member directory.",
      dashboardPriority: 21,
    },
    {
      href: "/chapter/students",
      label: "Chapter Students",
      icon: "🎓",
      roles: CHAPTER_PRESIDENT_ONLY,
      coreEligible: false,
      dashboardDescription: "Track student rosters, enrollment, and engagement.",
      dashboardPriority: 21,
      searchAliases: ["Students", "Student Roster"],
    },
    {
      href: "/chapter/instructors",
      label: "Chapter Instructors",
      icon: "👩‍🏫",
      roles: CHAPTER_PRESIDENT_ONLY,
      coreEligible: false,
      dashboardDescription: "Monitor instructor training, courses, and goals.",
      dashboardPriority: 21,
      searchAliases: ["Instructors", "Instructor Roster"],
    },
    {
      href: "/chapter/marketing",
      label: "Chapter Marketing",
      icon: "📊",
      roles: CHAPTER_PRESIDENT_ONLY,
      coreEligible: false,
      dashboardDescription: "Log outreach metrics and track growth goals.",
      dashboardPriority: 24,
      searchAliases: ["Marketing", "Outreach", "Growth"],
    },
    {
      href: "/chapter/leaderboard",
      label: "XP Leaderboard",
      icon: "🥇",
      dashboardDescription: "See who's leading in XP within your chapter.",
      dashboardPriority: 25,
    },
    {
      href: "/chapter/achievements",
      label: "Chapter Achievements",
      icon: "🎯",
      dashboardDescription: "Track your chapter's collective milestones and achievements.",
      dashboardPriority: 26,
    },
    {
      href: "/chapter/invites",
      label: "Invite Links",
      icon: "🔗",
      roles: CHAPTER_PRESIDENT_ONLY,
      dashboardDescription: "Create and manage shareable invite links to grow your chapter.",
      dashboardPriority: 23,
    },
    {
      href: "/chapters/leaderboard",
      label: "Network Chapter Leaderboard",
      icon: "🏆",
      dashboardDescription: "See how chapters across the network are growing.",
      dashboardPriority: 24,
    },
    {
      href: "/admin/chapters",
      label: "Chapter Directory",
      icon: "🏢",
      roles: ADMIN_ONLY,
      dashboardDescription: "Manage chapters, membership, and network-wide chapter settings in one place.",
      dashboardPriority: 3,
    },
    {
      href: "/chapter/settings",
      label: "Chapter Settings",
      icon: "⚙️",
      roles: CHAPTER_PRESIDENT_ONLY,
      dashboardDescription: "Customize your chapter profile, branding, and join policy.",
      dashboardPriority: 20,
    },
    {
      href: "/chapter-lead/instructor-applicants",
      label: "Chapter Applicants",
      icon: "📝",
      roles: CHAPTER_PRESIDENT_ONLY,
      dashboardDescription: "Review and manage instructor applications on your chapter's hiring board.",
      dashboardPriority: 6,
      searchAliases: ["Instructor Applicants", "Chapter Instructor Applicants"],
    },
    {
      href: "/chapter-lead/instructor-readiness",
      label: "Chapter Readiness",
      icon: "✅",
      roles: CHAPTER_PRESIDENT_ONLY,
      dashboardDescription: "Clear instructor training and interview blockers for your chapter.",
      dashboardPriority: 7,
      dashboardBadgeKey: "instructor_readiness_blockers",
      searchAliases: ["Instructor Readiness", "Chapter Instructor Readiness"],
    },
    {
      href: "/chapter-lead/portal-rollout",
      label: "Rollout Command",
      icon: "🗓",
      roles: CHAPTER_PRESIDENT_ONLY,
      dashboardDescription: "Track chapter rollout timeline, owners, and blockers.",
      dashboardPriority: 5,
    },
  ]),

  ...groupLinks("Profile & Settings", 1000, [
    { href: "/certificates", label: "My Certificates", icon: "📜" },
    {
      href: "/alumni",
      label: "Alumni Directory",
      icon: "🎓",
      requiresAward: true,
    },
    {
      href: "/college-advisor",
      label: "College Advisor",
      icon: "🧑‍💻",
      requiresAward: true,
    },
    {
      href: "/advisor-dashboard",
      label: "Advisor Dashboard",
      icon: "📋",
      requiresAward: true,
    },
    {
      href: "/profile",
      label: "My Profile",
      icon: "👤",
      hideForPrimaryRoles: ["INSTRUCTOR"],
    },
    { href: "/profile/timeline", label: "My Journey", icon: "🛤" },
    { href: "/profile/xp", label: "XP & Levels", icon: "⬆" },
    { href: "/profile/certifications", label: "Certifications", icon: "🏅" },
    { href: "/settings/personalization", label: "Profile & Settings", icon: "👤" },
    {
      href: "/notifications",
      label: "Notifications",
      icon: "🔔",
      badgeKey: "notifications",
      dashboardBadgeKey: "unread_notifications",
      dashboardDescription: "Review unread alerts and updates.",
      dashboardPriority: 10,
    },
  ]),

  ...groupLinks("Admin People", 1100, [
    { href: "/admin/students", label: "All Students", icon: "👨‍🎓", roles: ADMIN_ONLY },
    {
      href: "/admin/instructors",
      label: "All Instructors",
      icon: "👩‍🏫",
      roles: ADMIN_ONLY,
    },
    {
      href: "/admin/instructor-assignments",
      label: "Instructor Assignments",
      icon: "🧩",
      roles: ADMIN_ONLY,
      dashboardDescription: "Assign regular instructors to class offerings and track coverage.",
      dashboardPriority: 5,
      searchAliases: [
        "Regular Instructor Assignments",
        "Class Coverage",
        "Instructor Coverage",
      ],
    },
    { href: "/admin/bulk-users", label: "Bulk Users", icon: "👥", roles: ADMIN_ONLY },
    {
      href: "/admin/parent-approvals",
      label: "Parent Approvals",
      icon: "✔",
      roles: ADMIN_ONLY,
      badgeKey: "approvals",
      dashboardDescription: "Approve or reject pending parent-student link requests.",
      dashboardPriority: 4,
      dashboardBadgeKey: "pending_parent_approvals",
    },
    {
      href: "/admin/instructor-applicants",
      label: "Network Applicants",
      icon: "📝",
      roles: HIRING_CHAIR_ADMIN_ROLES,
      dashboardDescription: "Review and approve incoming instructor applications across all chapters.",
      dashboardPriority: 4,
      searchAliases: ["Instructor Applicants", "Network Instructor Applicants"],
      dashboardBadgeKey: "instructor_applicants",
    },
    {
      href: "/admin/instructor-applicants/chair-queue",
      label: "Hiring Chair Queue",
      icon: "⚖️",
      roles: HIRING_CHAIR_ADMIN_ROLES,
      badgeKey: "chairQueueCount",
      dashboardDescription: "Review applications awaiting hiring chair decision.",
      searchAliases: ["chair", "hiring chair", "decisions", "Chair Queue"],
    },
    {
      href: "/admin/chapter-president-applicants",
      label: "CP Applicants",
      icon: "👑",
      roles: ADMIN_ONLY,
      dashboardDescription: "Review and manage chapter president applications.",
      dashboardPriority: 4,
    },
    {
      href: "/admin/form-templates",
      label: "Form Templates",
      icon: "📝",
      roles: ADMIN_ONLY,
    },
    {
      href: "/admin/application-cohorts",
      label: "Application Cohorts",
      icon: "👥",
      roles: ADMIN_ONLY,
    },
    {
      href: "/admin/parent-feedback",
      label: "Parent Feedback",
      icon: "💬",
      roles: ADMIN_ONLY,
    },
    {
      href: "/admin/instructor-readiness",
      label: "Network Readiness",
      icon: "✅",
      roles: ADMIN_ONLY,
      dashboardDescription: "Resolve training, interview, and teaching-level readiness across all chapters.",
      dashboardPriority: 5,
      dashboardBadgeKey: "readiness_review_queue",
      searchAliases: ["Instructor Readiness", "Network Instructor Readiness"],
    },
    {
      href: "/admin/portal-rollout",
      label: "Rollout Command",
      icon: "🗓",
      roles: ADMIN_ONLY,
      dashboardDescription: "Track launch timeline, ownership, and blockers.",
      dashboardPriority: 6,
    },
    { href: "/admin/staff", label: "Staff Reflections", icon: "📝", roles: ADMIN_ONLY },
    {
      // Legacy Position-based hiring pipeline (Application/Decision models).
      // Distinct from the modern InstructorApplication board at
      // /admin/instructor-applicants. Relabeled to reduce confusion for admins
      // who saw two "Applications" entries side-by-side.
      href: "/admin/applications",
      label: "Position Applications (Legacy)",
      icon: "📋",
      roles: ADMIN_ONLY,
      dashboardDescription: "Legacy position-based hiring pipeline. Modern instructor applications live in Network Applicants.",
      dashboardPriority: 3,
      dashboardBadgeKey: "pending_app_decisions",
      searchAliases: ["Applications", "Hiring Pipeline"],
    },
    {
      href: "/admin/recruiting",
      label: "Recruiting Center",
      icon: "🧑‍💼",
      roles: ADMIN_ONLY,
      dashboardDescription: "Create chapter openings and monitor interview/decision flow.",
      dashboardPriority: 4,
      dashboardBadgeKey: "pending_app_decisions",
    },
  ]),

  ...groupLinks("Admin Content", 1200, [
    { href: "/admin/announcements", label: "Manage Updates", icon: "📢", roles: ADMIN_ONLY },
    { href: "/admin/rollout-comms", label: "Rollout Comms", icon: "✉️", roles: ADMIN_ONLY },
    { href: "/admin/programs", label: "Manage Programs", icon: "📦", roles: ADMIN_ONLY },
    { href: "/admin/training", label: "Training Modules", icon: "🏫", roles: ADMIN_ONLY },
    { href: "/admin/goals", label: "Goals", icon: "🎯", roles: ADMIN_ONLY },
    { href: "/admin/reflection-forms", label: "Reflection Forms", icon: "📋", roles: ADMIN_ONLY },
    { href: "/admin/challenges", label: "Challenges Mgmt", icon: "⚡", roles: ["ADMIN", "INSTRUCTOR", "CHAPTER_PRESIDENT"] },
    { href: "/admin/activities", label: "Activities Mgmt", icon: "🧭", roles: ["ADMIN", "INSTRUCTOR", "CHAPTER_PRESIDENT"] },
    { href: "/admin/passions", label: "Passion Areas", icon: "🌍", roles: ["ADMIN", "INSTRUCTOR", "CHAPTER_PRESIDENT"] },
    { href: "/admin/incubator", label: "Incubator Mgmt", icon: "🚀", roles: ["ADMIN", "INSTRUCTOR", "CHAPTER_PRESIDENT"] },
    {
      href: "/admin/curricula",
      label: "Curriculum Review",
      icon: "📝",
      roles: ["ADMIN", "CHAPTER_PRESIDENT"] as NavRole[],
      dashboardDescription: "Review and approve instructor-submitted curricula before they go live.",
      dashboardPriority: 8,
      dashboardBadgeKey: "pending_curriculum_review",
    },
    {
      href: "/admin/course-library",
      label: "Course Library",
      icon: "📚",
      roles: ADMIN_ONLY,
      dashboardDescription:
        "Curate the courses instructors pick from instead of building from scratch.",
      dashboardPriority: 7,
    },
    {
      href: "/admin/workshop-library",
      label: "Workshop Library",
      icon: "🎒",
      roles: ADMIN_ONLY,
      dashboardDescription: "Curate the workshops Summer Workshop applicants can pick from.",
      dashboardPriority: 9,
    },
    {
      href: "/admin/workshop-reviews",
      label: "Workshop Reviews",
      icon: "🧐",
      roles: ["ADMIN", "CHAPTER_PRESIDENT"] as NavRole[],
      dashboardDescription: "Score Summer Workshop Instructor proposals and committed decisions.",
      dashboardPriority: 9,
    },
    {
      href: "/admin/opportunities",
      label: "Workshop & Camp Assignments",
      icon: "🎯",
      roles: ADMIN_ONLY,
      dashboardDescription: "Manage partner camps and workshops, see uncovered slots, and assign instructors.",
      dashboardPriority: 9,
      searchAliases: [
        "Opportunities",
        "Camp Assignments",
        "Instructor Assignments",
        "Workshop Assignments",
      ],
    },
  ]),

  ...groupLinks("Admin Reports", 1300, [
    {
      href: "/admin/analytics",
      label: "Analytics",
      icon: "📈",
      roles: ADMIN_ONLY,
      dashboardDescription: "Monitor usage, outcomes, and platform health.",
      dashboardPriority: 22,
    },
    { href: "/admin/chapter-reports", label: "Chapter Reports", icon: "📊", roles: ADMIN_ONLY },
    { href: "/admin/pathway-tracking", label: "Pathway Tracking", icon: "🛤", roles: ADMIN_ONLY },
    { href: "/admin/pathways", label: "Manage Pathways", icon: "🗺", roles: ADMIN_ONLY },
    { href: "/admin/audit-log", label: "Audit Log", icon: "🗒", roles: ADMIN_ONLY },
    { href: "/admin/governance", label: "Governance & Risk", icon: "🛡", roles: ADMIN_ONLY },
    { href: "/admin/role-matrix", label: "Role Matrix Audit", icon: "👥", roles: ADMIN_ONLY },
    { href: "/admin/volunteer-hours", label: "Volunteer Hours", icon: "⏰", roles: ADMIN_ONLY },
    { href: "/admin/export", label: "Data Export", icon: "📥", roles: ADMIN_ONLY },
    { href: "/admin/data-export", label: "Export Tools", icon: "💾", roles: ADMIN_ONLY },
  ]),

  ...groupLinks("Admin Operations", 1400, [
    {
      href: "/admin/feature-gates",
      label: "Feature Access",
      icon: "🔑",
      roles: ADMIN_ONLY,
      dashboardDescription: "Grant or revoke per-user feature access (e.g., optional modules, Teaching Tools).",
    },
    {
      href: "/admin/hiring-committee",
      label: "Hiring Chair Queue",
      icon: "✅",
      roles: ADMIN_ONLY,
      dashboardDescription: "Approve or return hiring decisions before they are finalized.",
      dashboardBadgeKey: "pending_hiring_decisions",
    },
    {
      href: "/admin/waitlist",
      label: "Waitlist",
      icon: "⏳",
      roles: ADMIN_ONLY,
      dashboardDescription: "Process waitlist entries and enrollment offers.",
      dashboardPriority: 6,
      dashboardBadgeKey: "waitlist_waiting",
    },
    { href: "/admin/reminders", label: "Reminders", icon: "🔔", roles: ADMIN_ONLY },
    {
      href: "/admin/emergency-broadcast",
      label: "Emergency Broadcast",
      icon: "🚨",
      roles: ADMIN_ONLY,
    },
    {
      href: "/admin/mentorship",
      label: "Mentorship",
      icon: "🎯",
      roles: ADMIN_ONLY,
      dashboardDescription: "Oversee mentorship health, assignments, approvals, G&R, committees, and analytics.",
      dashboardPriority: 6,
    },
    { href: "/admin/alumni", label: "Manage Alumni", icon: "🎓", roles: ADMIN_ONLY },
    { href: "/admin/unlock-approvals", label: "Unlock Approvals", icon: "🔓", roles: ADMIN_ONLY, dashboardDescription: "Review and approve section unlock recommendations from mentors." },
    {
      href: "/admin/action-center",
      label: "Legacy Action Center",
      icon: "🎯",
      roles: ["ADMIN", "STAFF"] as NavRole[],
      requiresLegacyActionCenterNav: true,
      searchAliases: [
        "Leadership Action Center",
        "Officer Operations",
        "Weekly Action Tracker",
        "Legacy Action Items",
      ],
      dashboardDescription:
        "Deprecated legacy tracker retained only during migration to the People Strategy Action Tracker.",
      dashboardPriority: 3,
    },
  ]),
];
