import Link from "next/link";
import { pretty } from "@/lib/session8/format";

export function S8Page({ eyebrow, title, body, primaryHref, primaryLabel, children }: { eyebrow?: string; title: string; body: string; primaryHref?: string; primaryLabel?: string; children: React.ReactNode }) {
  return <main className="mx-auto max-w-7xl space-y-6 px-4 py-6 sm:px-6 lg:px-8">
    <section className="rounded-[2rem] border border-slate-200 bg-gradient-to-br from-white to-violet-50 p-6 shadow-sm">
      {eyebrow ? <p className="text-sm font-semibold uppercase tracking-wide text-violet-700">{eyebrow}</p> : null}
      <div className="mt-2 flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
        <div><h1 className="text-3xl font-bold tracking-tight text-slate-950">{title}</h1><p className="mt-2 max-w-3xl text-base text-slate-600">{body}</p></div>
        {primaryHref ? <Link className="inline-flex items-center justify-center rounded-full bg-violet-700 px-5 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-violet-800 focus:outline-none focus:ring-2 focus:ring-violet-500 focus:ring-offset-2" href={primaryHref}>{primaryLabel ?? "Open"}</Link> : null}
      </div>
    </section>{children}
  </main>
}
export function S8Grid({ children, cols = 3 }: { children: React.ReactNode; cols?: 2 | 3 | 4 }) { return <section className={`grid gap-4 ${cols===2?"lg:grid-cols-2":cols===4?"md:grid-cols-2 xl:grid-cols-4":"md:grid-cols-2 xl:grid-cols-3"}`}>{children}</section>; }
export function S8Card({ title, subtitle, actionHref, actionLabel, children }: { title: string; subtitle?: string; actionHref?: string; actionLabel?: string; children?: React.ReactNode }) { return <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-slate-950">{title}</h2>{subtitle ? <p className="mt-1 text-sm text-slate-500">{subtitle}</p> : null}</div>{actionHref ? <Link className="shrink-0 rounded-full border border-slate-200 px-3 py-1.5 text-sm font-semibold text-slate-700 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-violet-500" href={actionHref}>{actionLabel ?? "View"}</Link> : null}</div><div className="mt-4 space-y-3">{children}</div></article>; }
export function S8List({ items, empty, render }: { items: any[]; empty: string; render: (item:any)=>React.ReactNode }) { if (!items?.length) return <p className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-600">{empty}</p>; return <div className="space-y-3">{items.map(render)}</div>; }
export function S8Item({ title, meta, status, href, children }: { title: string; meta?: string; status?: string; href?: string; children?: React.ReactNode }) { const inner=<><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-semibold text-slate-950">{title}</p>{meta ? <p className="text-sm text-slate-500">{meta}</p> : null}</div>{status ? <span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-semibold text-violet-700">{pretty(status)}</span> : null}</div>{children ? <div className="mt-2 text-sm text-slate-600">{children}</div> : null}</>; return href ? <Link href={href} className="block rounded-2xl border border-slate-100 bg-slate-50 p-4 transition hover:border-violet-200 hover:bg-violet-50 focus:outline-none focus:ring-2 focus:ring-violet-500">{inner}</Link> : <div className="rounded-2xl border border-slate-100 bg-slate-50 p-4">{inner}</div>; }
export function S8FormButton({ children, formAction }: { children: React.ReactNode; formAction: (formData: FormData)=>Promise<void> }) { return <form action={formAction}><button className="rounded-full bg-slate-950 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-800 focus:outline-none focus:ring-2 focus:ring-violet-500" type="submit">{children}</button></form>; }
