import { beforeEach, describe, expect, it, vi } from "vitest";

const db: any = {
  classOffering: { findUnique: vi.fn(), update: vi.fn(), findMany: vi.fn() }, instructorAssignmentHistory: { updateMany: vi.fn(), create: vi.fn() }, classOfferingTimelineEvent: { create: vi.fn() }, notificationPreference: { findUnique: vi.fn() }, notification: { upsert: vi.fn(), create: vi.fn() }, operationalAuditEvent: { create: vi.fn() }, auditLog: { create: vi.fn() }, instructorApplication: { findFirst: vi.fn() }, instructorInterviewReview: { findFirst: vi.fn() }, instructorJourney: { findUnique: vi.fn() }, familyWaitlistEntry: { findUnique: vi.fn(), update: vi.fn(), findMany: vi.fn() }, classEnrollment: { count: vi.fn(), upsert: vi.fn(), update: vi.fn() }, guardianApprovalRequest: { findUnique: vi.fn(), update: vi.fn() }, familyFormVersion: { findFirst: vi.fn(), create: vi.fn() }, familyFormRequirement: { create: vi.fn(), update: vi.fn() }, familyFormSubmission: { update: vi.fn() }, familySupportRequest: { update: vi.fn() }, familySupportResponse: { create: vi.fn() }, classSession: { findUnique: vi.fn() }, classAttendanceRecord: { upsert: vi.fn() }, instructorSessionPreparation: { upsert: vi.fn() }, classAnnouncement: { findUnique: vi.fn(), update: vi.fn(), create: vi.fn() }, actionItem: { upsert: vi.fn(), updateMany: vi.fn(), create: vi.fn(), update: vi.fn() }, user: { findFirst: vi.fn() }, biweeklyActionPacket: { upsert: vi.fn() }, biweeklyActionPacketItem: { upsert: vi.fn() }, meetingDecision: { create: vi.fn() }, leadershipIntervention: { create: vi.fn() },
  $transaction: vi.fn(async (fn:any) => fn(db)),
};
vi.mock("@/lib/prisma", () => ({ prisma: db }));
vi.mock("@/lib/family-enrollment-service", () => ({ acceptWaitlistOffer: vi.fn(async()=>({ ok:true })) }));
const ops = await import("@/lib/session-4-operations");
const actor = { userId: "staff", roles: ["CHAPTER_PRESIDENT"], chapterIds: ["chap"] };
const admin = { userId: "admin", roles: ["ADMIN", "LEADERSHIP"] };

beforeEach(() => { vi.clearAllMocks(); db.instructorAssignmentHistory.updateMany.mockResolvedValue({count:0}); db.actionItem.updateMany.mockResolvedValue({count:1}); db.instructorAssignmentHistory.create.mockResolvedValue({}); db.classOfferingTimelineEvent.create.mockResolvedValue({}); db.classOffering.findUnique.mockResolvedValue({ id:"off", chapterId:"chap", instructorId:"old", capacity:2, enrollmentOpen:true, enrollments:[], title:"Class", template:{minStudents:1}, sessions:[], guardianApprovalRequests:[], familyFormRequirements:[], familySupportRequests:[] }); db.notificationPreference.findUnique.mockResolvedValue(null); db.notification.upsert.mockResolvedValue({}); db.operationalAuditEvent.create.mockResolvedValue({}); db.auditLog.create.mockResolvedValue({}); db.user.findFirst.mockResolvedValue({ id:"lead" }); });

describe("Session 4 operational mutations", () => {
 it("assigns, reassigns, removes, preserves history, notifies, audits, and resolves actions", async()=>{ db.instructorApplication.findFirst.mockResolvedValue({ status:"APPROVED" }); db.instructorInterviewReview.findFirst.mockResolvedValue({}); db.instructorJourney.findUnique.mockResolvedValue(null); await expect(ops.assignInstructor(actor,"off","inst","fit")).resolves.toEqual({ok:true}); expect(db.classOffering.update).toHaveBeenCalledWith({ where:{id:"off"}, data:{ instructorId:"inst" } }); expect(db.instructorAssignmentHistory.create).toHaveBeenCalled(); expect(db.notification.upsert).toHaveBeenCalled(); expect(db.actionItem.updateMany).toHaveBeenCalled(); await ops.removeInstructor(actor,"off","left"); expect(db.classOffering.update).toHaveBeenLastCalledWith({ where:{id:"off"}, data:{ instructorId:null } }); });
 it("blocks unreadiness unless override permission is present", async()=>{ db.instructorApplication.findFirst.mockResolvedValue({ status:"PENDING" }); db.instructorInterviewReview.findFirst.mockResolvedValue(null); await expect(ops.assignInstructor(actor,"off","inst","fit")).rejects.toThrow(/readiness/); await expect(ops.assignInstructor(admin,"off","inst","override",true)).resolves.toEqual({ok:true}); });
 it("performs transactional enrollment capacity, placement, close/reopen, and safe removal", async()=>{ db.classOffering.findUnique.mockResolvedValueOnce({ id:"off", chapterId:"chap" }).mockResolvedValueOnce({ id:"off", capacity:2, enrollments:[{status:"ENROLLED"}] }); db.classEnrollment.count.mockResolvedValue(1); await ops.updateEnrollmentOperations(actor,"off",{ capacity:3, enrollmentOpen:false, studentId:"stu", removeEnrollmentId:"enr", reason:"ops" }); expect(db.classEnrollment.upsert).toHaveBeenCalled(); expect(db.classEnrollment.update).toHaveBeenCalledWith({ where:{id:"enr"}, data:{status:"DROPPED", droppedAt: expect.any(Date)} }); });
 it("creates, declines, and expires waitlist offers with deduped notification/audit", async()=>{ db.familyWaitlistEntry.findUnique.mockResolvedValue({ id:"w", status:"ACTIVE", offeringId:"off", studentUserId:"stu", offering:{ title:"Class", capacity:2, enrollmentOpen:true, enrollments:[] } }); db.familyWaitlistEntry.update.mockResolvedValue({ id:"w" }); await ops.createWaitlistOffer(actor,"w",new Date(Date.now()+864e5),"seat"); expect(db.familyWaitlistEntry.update).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ status:"OFFERED" }) })); await ops.declineWaitlistOffer(actor,"w","no"); db.familyWaitlistEntry.findMany.mockResolvedValue([{id:"old"}]); await expect(ops.expireWaitlistOffers()).resolves.toBe(1); });
 it("decides guardian approvals and falls back to waitlist when full", async()=>{ db.guardianApprovalRequest.findUnique.mockResolvedValue({ id:"g", status:"PENDING", studentUserId:"stu", offeringId:"off", offering:{ capacity:1 } }); db.classEnrollment.count.mockResolvedValue(1); await ops.decideGuardianApproval(actor,"g","APPROVED","ok"); expect(db.classEnrollment.upsert).toHaveBeenCalledWith(expect.objectContaining({ update:{status:"WAITLISTED"} })); await expect(ops.decideGuardianApproval(actor,"g","DECLINED","no")).resolves.toEqual({ok:true}); });
 it("publishes immutable form versions, assigns requirements, reviews corrections and approvals", async()=>{ db.familyFormVersion.findFirst.mockResolvedValue({version:1}); db.familyFormVersion.create.mockResolvedValue({id:"v2",version:2}); await ops.publishFamilyFormVersion(actor,"tpl",{ fields:[] }); expect(db.familyFormVersion.create).toHaveBeenCalledWith({data:{templateId:"tpl",version:2,content:{fields:[]}}}); db.familyFormRequirement.create.mockResolvedValue({id:"req"}); await ops.assignFamilyFormRequirement(actor,{versionId:"v2",studentUserId:"stu",offeringId:"off",reason:"needed",staffReviewRequired:true}); db.familyFormSubmission.update.mockResolvedValue({id:"sub",requirementId:"req"}); await ops.reviewFamilyFormSubmission(actor,"sub","CORRECTION_REQUESTED","fix"); expect(db.familyFormRequirement.update).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ status:"IN_PROGRESS" }) })); });
 it("separates internal support comments from family-visible responses and supports safety routing", async()=>{ db.familySupportRequest.update.mockResolvedValue({id:"s"}); await ops.triageSupportRequest(actor,"s",{status:"REVIEWING",internalComment:"internal",familyResponse:"visible",safety:true}); expect(db.familySupportResponse.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ familyVisible:false, responseType:"SAFEGUARDING_RESTRICTED" }) })); expect(db.familySupportResponse.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ familyVisible:true }) })); });
 it("records attendance only for admitted students and writes audit", async()=>{ db.classOffering.findUnique.mockResolvedValue({ id:"off", chapterId:"chap", instructorId:"inst" }); db.classSession.findUnique.mockResolvedValue({ id:"sess", isCancelled:false, offeringId:"off", attendance:[], offering:{ instructorId:"inst", enrollments:[{studentId:"stu",status:"ENROLLED"},{studentId:"wait",status:"WAITLISTED"}] } }); await ops.recordAttendance({userId:"inst",roles:["INSTRUCTOR"]},"sess",[{studentId:"stu",status:"PRESENT"}]); expect(db.classAttendanceRecord.upsert).toHaveBeenCalled(); await expect(ops.recordAttendance({userId:"inst",roles:["INSTRUCTOR"]},"sess",[{studentId:"wait",status:"PRESENT"}])).rejects.toThrow(/waitlisted/); });
 it("updates session readiness and drafts/publishes announcements to admitted families only", async()=>{ db.classOffering.findUnique.mockResolvedValue({ id:"off", chapterId:"chap", instructorId:"inst" }); db.classSession.findUnique.mockResolvedValue({ id:"sess", offeringId:"off", offering:{ instructorId:"inst" } }); await ops.updateSessionReadiness({userId:"inst",roles:["INSTRUCTOR"]},"sess",{confirmReady:true, note:"ready"}); expect(db.instructorSessionPreparation.upsert).toHaveBeenCalled(); db.classAnnouncement.create.mockResolvedValue({id:"ann",offeringId:"off"}); await ops.upsertAnnouncement(actor,"off",{title:"Prep",body:"Bring notebook",announcementType:"CLASS_REMINDER"}); db.classAnnouncement.findUnique.mockResolvedValue({ id:"ann", title:"Prep", body:"Join", announcementType:"LOCATION_CHANGE", offeringId:"off", offering:{enrollments:[{studentId:"stu",status:"ENROLLED"},{studentId:"wait",status:"WAITLISTED"}]} }); db.classAnnouncement.update.mockResolvedValue({id:"ann"}); await ops.publishAnnouncement(actor,"ann"); expect(db.notification.upsert).toHaveBeenCalledTimes(1); });
 it("synchronizes deduped actions, packets, meeting decisions, and leadership interventions", async()=>{ db.actionItem.upsert.mockResolvedValue({id:"a",operationalSourceKey:"CLASS:off:INSTRUCTOR_MISSING",leadId:"lead",deadlineStart:new Date(),status:"NOT_STARTED"}); db.classOffering.findUnique.mockResolvedValueOnce({id:"off",title:"Class",chapterId:"chap",instructorId:null,template:{minStudents:1},sessions:[{id:"s",date:new Date(Date.now()+864e5),isCancelled:false}],enrollments:[],guardianApprovalRequests:[],familyFormRequirements:[],familySupportRequests:[]}); await ops.syncOperationalActionsForClass("off"); expect(db.actionItem.upsert).toHaveBeenCalled(); db.biweeklyActionPacket.upsert.mockResolvedValue({id:"p"}); db.classOffering.findMany.mockResolvedValue([{id:"off"}]); await ops.persistBiweeklyActionPacket(actor,"chap",new Date("2026-07-01"),new Date("2026-07-14")); expect(db.biweeklyActionPacketItem.upsert).toHaveBeenCalled(); db.meetingDecision.create.mockResolvedValue({id:"d"}); db.actionItem.create.mockResolvedValue({id:"a2",title:"Do it"}); await ops.createImpactDecision(actor,"m",{decision:"Decide",ownerId:"lead",chapterId:"chap"}); expect(db.notification.upsert).toHaveBeenCalled(); db.leadershipIntervention.create.mockResolvedValue({id:"li"}); await ops.createLeadershipIntervention(admin,{chapterId:"chap",sourceType:"ACTION_ITEM",sourceId:"a",createdById:"admin",note:"help"}); expect(db.leadershipIntervention.create).toHaveBeenCalled(); });
});
