"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { canGuardianManageCommunicationPreferences, canGuardianSignForms, canGuardianUpdateProfileField, canStudentUpdateProfileField, requireGuardianAccessToStudent, requireGuardianPortalUser, requireStudentPortalUser } from "@/lib/family-access";
import { acceptWaitlistOffer, assertGuardianCanManageEnrollment, decideGuardianApproval, enrollDirect, joinWaitlist, leaveWaitlist, requestGuardianApproval } from "@/lib/family-enrollment-service";

const text = (fd: FormData, k: string) => String(fd.get(k) ?? "").trim();
export async function studentOpportunityAction(fd: FormData) { const user = await requireStudentPortalUser(); const offeringId = text(fd,"offeringId"); const action = text(fd,"action"); if (action === "enroll") await enrollDirect(user.id, offeringId, { userId: user.id, role: "STUDENT" }); if (action === "approval") await requestGuardianApproval(user.id, offeringId, user.id); if (action === "waitlist") await joinWaitlist(user.id, offeringId, { userId: user.id, role: "STUDENT" }); if (action === "leaveWaitlist") await leaveWaitlist(user.id, offeringId, user.id); if (action === "acceptOffer") await acceptWaitlistOffer(user.id, offeringId, { userId: user.id, role: "STUDENT" }); revalidatePath("/student"); redirect(`/student/explore/${offeringId}`); }
export async function parentOpportunityAction(fd: FormData) { const user = await requireGuardianPortalUser(); const studentId = text(fd,"studentId"); const offeringId = text(fd,"offeringId"); const action = text(fd,"action"); await assertGuardianCanManageEnrollment(user.id, studentId); if (action === "enroll") await enrollDirect(studentId, offeringId, { userId: user.id, role: "GUARDIAN" }); if (action === "waitlist") await joinWaitlist(studentId, offeringId, { userId: user.id, role: "GUARDIAN" }); if (action === "leaveWaitlist") await leaveWaitlist(studentId, offeringId, user.id); if (action === "acceptOffer") await acceptWaitlistOffer(studentId, offeringId, { userId: user.id, role: "GUARDIAN" }); revalidatePath("/parent"); redirect(`/parent/explore/${offeringId}?studentId=${studentId}`); }
export async function guardianApprovalDecisionAction(fd: FormData) { const user = await requireGuardianPortalUser(); await decideGuardianApproval(user.id, text(fd,"requestId"), text(fd,"decision") as any, text(fd,"note")); revalidatePath("/parent"); }
export async function createStudentSupportRequest(fd: FormData) { const user = await requireStudentPortalUser(); const category = text(fd,"category"); const safety = category === "I do not feel comfortable"; await (prisma as any).familySupportRequest.create({ data: { requesterUserId: user.id, requesterRole: "STUDENT", studentUserId: user.id, category, description: text(fd,"description"), offeringId: text(fd,"offeringId") || null, sessionId: text(fd,"sessionId") || null, internalRoutingTeam: safety ? "SAFEGUARDING" : "FAMILY_SUPPORT", safetyFlag: safety, histories: { create: { status: "SENT", actorUserId: user.id } } } }); revalidatePath("/student/support"); }
export async function createParentSupportRequest(fd: FormData) { const user = await requireGuardianPortalUser(); const studentId = text(fd,"studentId") || null; if (studentId) { const rel = await requireGuardianAccessToStudent(user.id, studentId); if (!(rel as any).canSubmitSupportRequests) throw new Error("You do not have permission to submit support requests."); } const category = text(fd,"category"); const safety = category === "safety concern"; await (prisma as any).familySupportRequest.create({ data: { requesterUserId: user.id, requesterRole: "GUARDIAN", guardianUserId: user.id, studentUserId: studentId, category, description: text(fd,"description"), offeringId: text(fd,"offeringId") || null, sessionId: text(fd,"sessionId") || null, internalRoutingTeam: safety ? "SAFEGUARDING" : "FAMILY_SUPPORT", safetyFlag: safety, histories: { create: { status: "SENT", actorUserId: user.id } } } }); revalidatePath("/parent/support"); }
export async function signFamilyFormAction(fd: FormData) { const user = await requireGuardianPortalUser(); const requirementId = text(fd,"requirementId"); const req = await (prisma as any).familyFormRequirement.findUnique({ where: { id: requirementId }, include: { version: { include: { template: true } } } }); if (!req) throw new Error("Form requirement not found."); const rel = await requireGuardianAccessToStudent(user.id, req.studentUserId); if (!canGuardianSignForms(rel as any)) throw new Error("You do not have permission to sign forms."); await prisma.$transaction(async (tx: any) => { const submission = await tx.familyFormSubmission.create({ data: { requirementId, versionId: req.versionId, studentUserId: req.studentUserId, guardianUserId: user.id, guardianRelationshipId: rel.id.startsWith("legacy:") ? null : rel.id, content: { acknowledgement: true }, signatures: { create: { versionId: req.versionId, guardianUserId: user.id, studentUserId: req.studentUserId, guardianRelationshipId: rel.id.startsWith("legacy:") ? null : rel.id, signerName: user.name, acknowledgementText: `I acknowledge ${req.version.template.title} version ${req.version.version}.` } } } }); await tx.familyFormRequirement.update({ where: { id: requirementId }, data: { status: "COMPLETED", completedAt: new Date() } }); return submission; }); revalidatePath("/parent/forms"); }
export async function updateStudentProfileAction(fd: FormData) { const user = await requireStudentPortalUser(); const field = text(fd,"field"); if (!canStudentUpdateProfileField(user.id, user.id, field)) throw new Error("This field is not student-editable."); await (prisma as any).userProfile.update({ where: { userId: user.id }, data: { [field]: field === "interests" ? text(fd,"value").split(",").map((v)=>v.trim()).filter(Boolean) : text(fd,"value") } }); revalidatePath("/student/profile"); }
export async function updateCommunicationPreferenceAction(fd: FormData) { const user = await requireGuardianPortalUser(); const studentId = text(fd,"studentId") || null; if (studentId) { const rel = await requireGuardianAccessToStudent(user.id, studentId); if (!canGuardianManageCommunicationPreferences(rel as any)) throw new Error("You do not have permission to manage communication preferences."); } const topic = text(fd,"topic"); const enabled = fd.get("enabled") === "on" || ["schedule_changes","safety_notices","enrollment_decisions","required_forms"].includes(topic); const gp = await (prisma as any).guardianProfile.findUnique({ where: { userId: user.id } }); if (!gp) throw new Error("Guardian profile not found."); await (prisma as any).communicationPreference.upsert({ where: { guardianProfileId_studentUserId_channel_topic: { guardianProfileId: gp.id, studentUserId: studentId, channel: text(fd,"channel") || "EMAIL", topic } }, update: { enabled }, create: { guardianProfileId: gp.id, studentUserId: studentId, channel: text(fd,"channel") || "EMAIL", topic, enabled } }); revalidatePath("/parent/settings"); }
export async function saveEmergencyContactAction(fd: FormData) { const user = await requireGuardianPortalUser(); const studentId = text(fd,"studentId"); const rel = await requireGuardianAccessToStudent(user.id, studentId); if (!(rel as any).canUpdateContactInformation) throw new Error("You do not have permission to update emergency contacts."); const gp = await (prisma as any).guardianProfile.findUnique({ where: { userId: user.id } }); const id = text(fd,"contactId"); const data = { studentUserId: studentId, guardianProfileId: gp?.id, name: text(fd,"name"), relationshipType: text(fd,"relationshipType"), phone: text(fd,"phone"), email: text(fd,"email"), priority: Number(text(fd,"priority") || 0), isAuthorizedPickup: fd.get("isAuthorizedPickup") === "on" }; if (id) await (prisma as any).emergencyContact.update({ where: { id }, data }); else await (prisma as any).emergencyContact.create({ data }); revalidatePath("/parent/settings"); }
export async function archiveEmergencyContactAction(fd: FormData) { const user = await requireGuardianPortalUser(); const contact = await (prisma as any).emergencyContact.findUnique({ where: { id: text(fd,"contactId") } }); if (!contact) throw new Error("Contact not found."); const rel = await requireGuardianAccessToStudent(user.id, contact.studentUserId); if (!(rel as any).canUpdateContactInformation) throw new Error("You do not have permission to update emergency contacts."); await (prisma as any).emergencyContact.update({ where: { id: contact.id }, data: { archivedAt: new Date() } }); revalidatePath("/parent/settings"); }
export async function updateGuardianStudentProfileAction(fd: FormData) { const user = await requireGuardianPortalUser(); const studentId = text(fd,"studentId"); const field = text(fd,"field"); const rel = await requireGuardianAccessToStudent(user.id, studentId); if (!canGuardianUpdateProfileField(rel as any, field)) { await (prisma as any).familySupportRequest.create({ data: { requesterUserId: user.id, requesterRole: "GUARDIAN", guardianUserId: user.id, studentUserId: studentId, category: "student information update", description: `Review requested for ${field}.`, internalRoutingTeam: "FAMILY_SUPPORT" } }); } else await (prisma as any).userProfile.update({ where: { userId: studentId }, data: { [field]: text(fd,"value") } }); revalidatePath("/parent/settings"); }
