import { prisma } from "@/lib/prisma";
import { deriveClassLifecycle, getChapterClassPipeline, getClassOperations } from "@/lib/class-lifecycle-service";
import { filterStudentFacingRecord, filterGuardianFacingRecord } from "@/lib/family-access";

export function instructorRosterDto(enrollment: any) { return { enrollmentId: enrollment.id, status: enrollment.status, student: { id: enrollment.student?.id, name: enrollment.student?.name, gradeLevel: enrollment.student?.profile?.gradeLevel ?? null }, attendance: (enrollment.student?.attendance ?? []).map((a:any)=>({ sessionId: a.sessionId, status: a.status })) }; }
export function chapterClassDto(ops: any) { return { id: ops.offering.id, title: ops.offering.title, lifecycle: ops.lifecycle, students: ops.offering.enrollments?.map((e:any)=>({ id: e.student?.id, name: e.student?.name, status: e.status })), support: ops.offering.familySupportRequests?.map((r:any)=>({ id: r.id, category: r.category, status: r.status, safetyRestricted: r.safetyRestricted, internalOwnerId: r.internalOwnerId })) }; }
export function leadershipChapterDto(pipeline: any[]) { return pipeline.map((lane:any)=>({ stage: lane.stage, label: lane.label, count: lane.items.length, blockers: lane.items.map((i:any)=>({ offeringId: i.offeringId, title: i.title, blocker: i.blocker?.label ?? null, owner: i.owner })) })); }
export function studentClassDto(record: any) { return filterStudentFacingRecord(record); }
export function guardianStudentDto(record: any) { return filterGuardianFacingRecord(record); }

export async function getInstructorOperations(instructorId: string) {
  const offerings = await (prisma as any).classOffering.findMany({ where: { instructorId, status: { in: ["PUBLISHED", "IN_PROGRESS"] } }, include: { template: true, sessions: { include: { attendance: true }, orderBy: [{ date: "asc" }] }, enrollments: { where: { status: { in: ["ENROLLED", "COMPLETED"] } }, include: { student: { select: { id: true, name: true, profile: true } } } }, announcements: { where: { status: "PUBLISHED" }, orderBy: { createdAt: "desc" } } } });
  return offerings.map((offering:any)=>({ id: offering.id, title: offering.title, lifecycle: deriveClassLifecycle(offering), roster: offering.enrollments.map(instructorRosterDto), sessions: offering.sessions.map((s:any)=>({ id: s.id, topic: s.topic, date: s.date, attendanceRecorded: s.attendance?.length > 0, isCancelled: s.isCancelled })) }));
}
export async function getChapterHomeOperations(chapterId: string) { const pipeline = await getChapterClassPipeline(chapterId); return { pipeline, today: pipeline.flatMap((l:any)=>l.items).filter((i:any)=>i.blocker).slice(0, 8) }; }
export async function getLeadershipChapterOversight(chapterId: string) { return leadershipChapterDto(await getChapterClassPipeline(chapterId)); }
export async function getBiweeklyActionPacket(chapterId: string, now = new Date()) { const pipeline = await getChapterClassPipeline(chapterId); const dueAt = new Date(now); dueAt.setDate(dueAt.getDate()+14); return pipeline.flatMap((lane:any)=>lane.items.filter((i:any)=>i.blocker || i.nextSession).map((i:any)=>({ key: `${chapterId}:${i.offeringId}:${i.blocker?.code ?? 'NEXT_SESSION'}`, action: i.blocker?.label ?? `Prepare for ${i.title}`, why: i.blocker ? "This blocks class execution." : "The next session is within the two-week operating window.", offeringId: i.offeringId, owner: i.owner, dueAt, status: i.blocker ? "OPEN" : "READY", href: i.href }))); }
export async function getImpactMeetingPreparation(chapterId: string) { const [packet, meetings] = await Promise.all([getBiweeklyActionPacket(chapterId), (prisma as any).meeting.findMany({ where: { chapterId, type: "CHAPTER_IMPACT" }, include: { decisions: true, followUps: true }, orderBy: { scheduledAt: "desc" }, take: 3 }).catch(()=>[])]); return { packet, decisionsNeeded: packet.filter((i:any)=>i.status === "OPEN"), recentMeetings: meetings }; }
export async function getClassOperationsDto(offeringId: string) { const ops = await getClassOperations(offeringId); return ops ? chapterClassDto(ops) : null; }
