import { prisma } from "@/lib/prisma";
import { acceptWaitlistOffer as familyAcceptWaitlistOffer } from "@/lib/family-enrollment-service";
import { deriveClassLifecycle } from "@/lib/class-lifecycle-service";
import { auditOperationalEvent } from "@/lib/operational-audit-service";
import { notifyOperational } from "@/lib/operational-notification-service";
import { canOverrideReadiness, canPublishAnnouncement, requireInstructorAssigned, requireOfferingScope, type Session4Actor } from "@/lib/operational-permissions";

const nowPlus = (days: number) => { const d = new Date(); d.setDate(d.getDate() + days); return d; };
const activeStatuses = ["ENROLLED", "COMPLETED"];
async function actionLead(chapterId?: string | null) { const u = await (prisma as any).user.findFirst({ where: { OR: [{ roles: { some: { role: "CHAPTER_PRESIDENT" } } }, { roles: { some: { role: "ADMIN" } } }] } }).catch(()=>null); return u?.id ?? "system"; }

export async function getInstructorReadiness(instructorId: string) {
  const [app, interview, prep] = await Promise.all([
    (prisma as any).instructorApplication.findFirst({ where: { userId: instructorId }, orderBy: { createdAt: "desc" } }).catch(()=>null),
    (prisma as any).instructorInterviewReview.findFirst({ where: { instructorId }, orderBy: { createdAt: "desc" } }).catch(()=>null),
    (prisma as any).instructorJourney.findUnique({ where: { userId: instructorId } }).catch(()=>null),
  ]);
  const missing: string[] = [];
  if (app && !["APPROVED", "ACCEPTED", "HIRED"].includes(app.status)) missing.push("Application not approved");
  if (!interview) missing.push("Interview incomplete");
  if (prep && !["COMPLETE", "COMPLETED"].includes(prep.status ?? prep.onboardingStatus ?? "")) missing.push("Onboarding incomplete");
  return { ready: missing.length === 0, missing, applicationStatus: app?.status ?? null, interviewComplete: Boolean(interview), onboardingStatus: prep?.status ?? null };
}
export async function listEligibleInstructorCandidates(offeringId: string) {
  const offering = await (prisma as any).classOffering.findUnique({ where: { id: offeringId }, include: { template: true } });
  const users = await (prisma as any).user.findMany({ where: { roles: { some: { role: "INSTRUCTOR" } } }, take: 25, orderBy: { name: "asc" } });
  return Promise.all(users.map(async (u:any)=>({ id: u.id, name: u.name, email: u.email, readiness: await getInstructorReadiness(u.id), programFit: offering?.template?.interestArea ? `Matched to ${offering.template.interestArea} review` : "General instructor" })));
}
export async function assignInstructor(actor: Session4Actor, offeringId: string, instructorId: string, reason: string, overrideReadiness = false) {
  if (!reason?.trim()) throw new Error("Assignment reason is required");
  await requireOfferingScope(actor, offeringId);
  const readiness = await getInstructorReadiness(instructorId);
  if (!readiness.ready && (!overrideReadiness || !canOverrideReadiness(actor.roles))) throw new Error(`Instructor readiness incomplete: ${readiness.missing.join(", ")}`);
  return (prisma as any).$transaction(async (tx:any)=>{
    const before = await tx.classOffering.findUnique({ where: { id: offeringId }, select: { instructorId: true, title: true } });
    await tx.classOffering.update({ where: { id: offeringId }, data: { instructorId } });
    await tx.instructorAssignmentHistory.updateMany({ where: { offeringId, active: true }, data: { active: false, removedAt: new Date() } }).catch(()=>null);
    await tx.instructorAssignmentHistory.create({ data: { offeringId, previousInstructorId: before?.instructorId ?? null, newInstructorId: instructorId, actorUserId: actor.userId, reason, readinessOverride: overrideReadiness, readinessSnapshot: readiness } }).catch(()=>null);
    await tx.classOfferingTimelineEvent.create({ data: { offeringId, actorId: actor.userId, kind: "INSTRUCTOR_REASSIGNED", summary: before?.instructorId ? "Instructor reassigned" : "Instructor assigned", payload: { previousInstructorId: before?.instructorId, newInstructorId: instructorId, reason, readiness } } });
    await auditOperationalEvent({ actorUserId: actor.userId, action: before?.instructorId ? "INSTRUCTOR_REASSIGNED" : "INSTRUCTOR_ASSIGNED", sourceType: "CLASS_OFFERING", sourceId: offeringId, previousState: before, newState: { instructorId }, reason });
    await notifyOperational({ userId: instructorId, eventType: "INSTRUCTOR_CLASS_ASSIGNED", title: "You were assigned to a class", body: before?.title ?? "A YPP class was assigned to you.", link: `/instructor/classes/${offeringId}`, relatedEntityType: "CLASS_OFFERING", relatedEntityId: offeringId, dedupeKey: `class-assigned:${offeringId}:${instructorId}`, operational: true });
    await resolveOperationalAction(offeringId, "INSTRUCTOR_MISSING", actor.userId);
    return { ok: true };
  });
}
export async function removeInstructor(actor: Session4Actor, offeringId: string, reason: string) {
  if (!reason?.trim()) throw new Error("Removal reason is required");
  await requireOfferingScope(actor, offeringId);
  return (prisma as any).$transaction(async (tx:any)=>{ const before = await tx.classOffering.findUnique({ where:{id:offeringId}, select:{ instructorId:true } }); await tx.classOffering.update({ where:{id:offeringId}, data:{ instructorId: null } }); await tx.instructorAssignmentHistory.updateMany({ where:{ offeringId, active:true }, data:{ active:false, removedAt:new Date() } }).catch(()=>null); await tx.instructorAssignmentHistory.create({ data:{ offeringId, previousInstructorId: before?.instructorId, newInstructorId:null, actorUserId:actor.userId, reason, active:false, removedAt:new Date() } }).catch(()=>null); await tx.classOfferingTimelineEvent.create({ data:{ offeringId, actorId:actor.userId, kind:"INSTRUCTOR_REASSIGNED", summary:"Instructor removed", payload:{ previousInstructorId: before?.instructorId, reason } } }); await auditOperationalEvent({ actorUserId:actor.userId, action:"INSTRUCTOR_REMOVED", sourceType:"CLASS_OFFERING", sourceId:offeringId, previousState:before, newState:{ instructorId:null }, reason }); return { ok:true }; });
}
export async function updateEnrollmentOperations(actor: Session4Actor, offeringId: string, input: { enrollmentOpen?: boolean; capacity?: number; studentId?: string; removeEnrollmentId?: string; reason: string }) {
  if (!input.reason?.trim()) throw new Error("Reason is required"); await requireOfferingScope(actor, offeringId);
  return (prisma as any).$transaction(async(tx:any)=>{ const off=await tx.classOffering.findUnique({where:{id:offeringId},include:{enrollments:true}}); if(!off) throw new Error("Class not found"); const data:any={}; if(typeof input.enrollmentOpen==='boolean') data.enrollmentOpen=input.enrollmentOpen; if(input.capacity!==undefined){ const current=off.enrollments.filter((e:any)=>e.status==="ENROLLED").length; if(input.capacity<current) throw new Error("Capacity cannot be below current admitted enrollment"); data.capacity=input.capacity; } if(Object.keys(data).length) await tx.classOffering.update({where:{id:offeringId},data}); if(input.studentId){ const current=await tx.classEnrollment.count({where:{offeringId,status:"ENROLLED"}}); if(current >= (data.capacity ?? off.capacity)) throw new Error("Class is full"); await tx.classEnrollment.upsert({where:{studentId_offeringId:{studentId:input.studentId,offeringId}},update:{status:"ENROLLED",droppedAt:null},create:{studentId:input.studentId,offeringId,status:"ENROLLED",outcomesAchieved:[]}}); }
  if(input.removeEnrollmentId) await tx.classEnrollment.update({where:{id:input.removeEnrollmentId},data:{status:"DROPPED",droppedAt:new Date()}}); await tx.classOfferingTimelineEvent.create({data:{offeringId,actorId:actor.userId,kind: input.capacity!==undefined?"CAPACITY_CHANGED":"ENROLLMENT_STATUS_CHANGED",summary:"Enrollment operation",payload:input}}); await auditOperationalEvent({actorUserId:actor.userId,action:"ENROLLMENT_OPERATION",sourceType:"CLASS_OFFERING",sourceId:offeringId,newState:input,reason:input.reason}); return {ok:true}; });
}
export async function createWaitlistOffer(actor: Session4Actor, waitlistId: string, expiresAt: Date, note?: string) {
  const entry=await (prisma as any).familyWaitlistEntry.findUnique({where:{id:waitlistId},include:{offering:{include:{enrollments:true}},studentUser:true}}); if(!entry||entry.status!=="ACTIVE") throw new Error("Active waitlist entry required"); await requireOfferingScope(actor, entry.offeringId); if(!entry.offering.enrollmentOpen) throw new Error("Enrollment is closed"); if(entry.offering.enrollments.filter((e:any)=>e.status==="ENROLLED").length>=entry.offering.capacity) throw new Error("No capacity available"); return (prisma as any).familyWaitlistEntry.update({where:{id:waitlistId},data:{status:"OFFERED",offerExpiresAt:expiresAt,decidedById:actor.userId,audits:{create:{actorUserId:actor.userId,action:"OFFERED",note}}}}).then(async(r:any)=>{ await notifyOperational({userId:entry.studentUserId,eventType:"WAITLIST_OFFER_CREATED",title:"A seat is available",body:`A seat opened for ${entry.offering.title}.`,link:`/student/classes/${entry.offeringId}`,relatedEntityType:"FAMILY_WAITLIST_ENTRY",relatedEntityId:waitlistId,dedupeKey:`waitlist-offer:${waitlistId}`}); await auditOperationalEvent({actorUserId:actor.userId,action:"WAITLIST_OFFER_CREATED",sourceType:"FAMILY_WAITLIST_ENTRY",sourceId:waitlistId,newState:{expiresAt},reason:note}); return r; });
}
export async function acceptStaffWaitlistOffer(actor: Session4Actor, waitlistId: string) { const e=await (prisma as any).familyWaitlistEntry.findUnique({where:{id:waitlistId}}); if(!e) throw new Error("Offer not found"); return familyAcceptWaitlistOffer(e.studentUserId,e.offeringId,({userId:actor.userId, role:"GUARDIAN"} as any)); }
export async function declineWaitlistOffer(actor: Session4Actor, waitlistId: string, note?: string) { const e=await (prisma as any).familyWaitlistEntry.update({where:{id:waitlistId},data:{status:"DECLINED",decidedById:actor.userId,audits:{create:{actorUserId:actor.userId,action:"DECLINED",note}}}}); await auditOperationalEvent({actorUserId:actor.userId,action:"WAITLIST_DECLINED",sourceType:"FAMILY_WAITLIST_ENTRY",sourceId:waitlistId,reason:note}); return e; }
export async function expireWaitlistOffers() { const rows=await (prisma as any).familyWaitlistEntry.findMany({where:{status:"OFFERED",offerExpiresAt:{lt:new Date()}}}); for(const r of rows) await (prisma as any).familyWaitlistEntry.update({where:{id:r.id},data:{status:"EXPIRED",audits:{create:{action:"EXPIRED",note:"Deterministic Session 4 expiration"}}}}); return rows.length; }
export async function decideGuardianApproval(actor: Session4Actor, requestId: string, decision: "APPROVED"|"DECLINED", note?: string) { const req=await (prisma as any).guardianApprovalRequest.findUnique({where:{id:requestId},include:{offering:true}}); if(!req||req.status!=="PENDING") throw new Error("Pending request required"); return (prisma as any).$transaction(async(tx:any)=>{ await tx.guardianApprovalRequest.update({where:{id:requestId},data:{status:decision,decisionById:actor.userId,decisionNote:note,decidedAt:new Date()}}); if(decision==="APPROVED"){ const count=await tx.classEnrollment.count({where:{offeringId:req.offeringId,status:"ENROLLED"}}); if(count<req.offering.capacity) await tx.classEnrollment.upsert({where:{studentId_offeringId:{studentId:req.studentUserId,offeringId:req.offeringId}},update:{status:"ENROLLED"},create:{studentId:req.studentUserId,offeringId:req.offeringId,status:"ENROLLED",outcomesAchieved:[]}}); else await tx.classEnrollment.upsert({where:{studentId_offeringId:{studentId:req.studentUserId,offeringId:req.offeringId}},update:{status:"WAITLISTED"},create:{studentId:req.studentUserId,offeringId:req.offeringId,status:"WAITLISTED",outcomesAchieved:[]}}); } await auditOperationalEvent({actorUserId:actor.userId,action:`GUARDIAN_APPROVAL_${decision}`,sourceType:"GUARDIAN_APPROVAL_REQUEST",sourceId:requestId,reason:note}); return {ok:true}; }); }
export async function publishFamilyFormVersion(actor: Session4Actor, templateId: string, content: any) { const latest=await (prisma as any).familyFormVersion.findFirst({where:{templateId},orderBy:{version:"desc"}}); const v=(latest?.version??0)+1; const row=await (prisma as any).familyFormVersion.create({data:{templateId,version:v,content}}); await auditOperationalEvent({actorUserId:actor.userId,action:"FORM_VERSION_PUBLISHED",sourceType:"FAMILY_FORM_TEMPLATE",sourceId:templateId,newState:{version:v}}); return row; }
export async function assignFamilyFormRequirement(actor: Session4Actor, input:any) { await requireOfferingScope(actor,input.offeringId); const row=await (prisma as any).familyFormRequirement.create({data:{versionId:input.versionId,studentUserId:input.studentUserId,offeringId:input.offeringId,dueAt:input.dueAt,reason:input.reason,blocksEnrollment:!!input.blocksEnrollment,blocksAttendance:!!input.blocksAttendance,staffReviewRequired:!!input.staffReviewRequired}}); await notifyOperational({userId:input.studentUserId,eventType:"FORM_REQUIRED",title:"A family form is required",body:input.reason,link:"/parent/forms",relatedEntityType:"FAMILY_FORM_REQUIREMENT",relatedEntityId:row.id,dedupeKey:`form-required:${row.id}`}); return row; }
export async function reviewFamilyFormSubmission(actor: Session4Actor, submissionId:string, decision:"APPROVED"|"CORRECTION_REQUESTED"|"WAIVED", note:string){ const sub=await (prisma as any).familyFormSubmission.update({where:{id:submissionId},data:{staffReviewState:decision,reviewedById:actor.userId,reviewedAt:new Date(),reviewNote:note}}); await (prisma as any).familyFormRequirement.update({where:{id:sub.requirementId},data:{status:decision==="APPROVED"?"COMPLETED":decision==="WAIVED"?"WAIVED":"IN_PROGRESS",completedAt:decision==="APPROVED"?new Date():undefined}}); await auditOperationalEvent({actorUserId:actor.userId,action:`FORM_${decision}`,sourceType:"FAMILY_FORM_SUBMISSION",sourceId:submissionId,reason:note}); return sub; }
export async function triageSupportRequest(actor: Session4Actor, requestId:string, input:any){ const row=await (prisma as any).familySupportRequest.update({where:{id:requestId},data:{internalOwnerId:input.ownerId,internalRoutingTeam:input.team,internalCategory:input.category,internalSeverity:input.severity,externalStatus:input.status,internalActionItemId:input.actionItemId,resolvedAt:["RESOLVED","CLOSED"].includes(input.status)?new Date():undefined,histories:{create:{status:input.status,actorUserId:actor.userId,note:input.note}}}}); if(input.internalComment) await (prisma as any).familySupportResponse.create({data:{requestId,authorUserId:actor.userId,body:input.internalComment,familyVisible:false,responseType: input.safety ? "SAFEGUARDING_RESTRICTED":"INTERNAL_NOTE"}}); if(input.familyResponse) await (prisma as any).familySupportResponse.create({data:{requestId,authorUserId:actor.userId,body:input.familyResponse,familyVisible:true,responseType:"FAMILY_VISIBLE"}}); await auditOperationalEvent({actorUserId:actor.userId,action:"SUPPORT_TRIAGED",sourceType:"FAMILY_SUPPORT_REQUEST",sourceId:requestId,newState:input}); return row; }
export async function recordAttendance(actor: Session4Actor, sessionId:string, records:{studentId:string;status:string;notes?:string}[], finalize=true){ const session=await (prisma as any).classSession.findUnique({where:{id:sessionId},include:{offering:{include:{enrollments:true}}}}); if(!session||session.isCancelled) throw new Error("Active session required"); await requireInstructorAssigned(actor,session.offeringId); const admitted=new Set(session.offering.enrollments.filter((e:any)=>activeStatuses.includes(e.status)).map((e:any)=>e.studentId)); for(const r of records){ if(!admitted.has(r.studentId)) throw new Error("Cannot record attendance for waitlisted or dropped students"); await (prisma as any).classAttendanceRecord.upsert({where:{sessionId_studentId:{sessionId,studentId:r.studentId}},update:{status:r.status,notes:r.notes,checkedInAt:new Date()},create:{sessionId,studentId:r.studentId,status:r.status,notes:r.notes}}); } await auditOperationalEvent({actorUserId:actor.userId,action:"ATTENDANCE_RECORDED",sourceType:"CLASS_SESSION",sourceId:sessionId,newState:{records,finalize}}); return {ok:true}; }
export async function updateSessionReadiness(actor: Session4Actor, sessionId:string, input:any){ const s=await (prisma as any).classSession.findUnique({where:{id:sessionId},include:{offering:true}}); if(!s) throw new Error("Session not found"); await requireInstructorAssigned(actor,s.offeringId); const prep=await (prisma as any).instructorSessionPreparation.upsert({where:{sessionId_instructorId:{sessionId,instructorId:s.offering.instructorId}},update:{note:input.note,lessonReviewedAt:input.lessonReviewed?new Date():undefined,materialsReviewedAt:input.materialsReviewed?new Date():undefined,studentContextReviewedAt:input.studentContextReviewed?new Date():undefined,completedAt:input.confirmReady?new Date():undefined},create:{sessionId,instructorId:s.offering.instructorId,note:input.note,lessonReviewedAt:input.lessonReviewed?new Date():undefined,materialsReviewedAt:input.materialsReviewed?new Date():undefined,studentContextReviewedAt:input.studentContextReviewed?new Date():undefined,completedAt:input.confirmReady?new Date():undefined}}); await auditOperationalEvent({actorUserId:actor.userId,action:"SESSION_READINESS_UPDATED",sourceType:"CLASS_SESSION",sourceId:sessionId,newState:input}); return prep; }
export async function upsertAnnouncement(actor: Session4Actor, offeringId:string, input:any){ await requireOfferingScope(actor,offeringId); const approvalRequired=!canPublishAnnouncement(actor.roles,input.announcementType); const data={authorId:actor.userId,title:input.title,body:input.body,announcementType:input.announcementType,audience:input.audience??"ADMITTED_FAMILIES",status:input.status??"DRAFT",approvalRequired,sessionId:input.sessionId}; const row=input.id?await (prisma as any).classAnnouncement.update({where:{id:input.id},data}):await (prisma as any).classAnnouncement.create({data:{offeringId,...data}}); await auditOperationalEvent({actorUserId:actor.userId,action:"ANNOUNCEMENT_DRAFTED",sourceType:"CLASS_ANNOUNCEMENT",sourceId:row.id,newState:data}); return row; }
export async function publishAnnouncement(actor: Session4Actor, announcementId:string){ const a=await (prisma as any).classAnnouncement.findUnique({where:{id:announcementId},include:{offering:{include:{enrollments:true}}}}); if(!a) throw new Error("Announcement not found"); if(!canPublishAnnouncement(actor.roles,a.announcementType)) throw new Error("Publishing this announcement requires chapter approval"); const row=await (prisma as any).classAnnouncement.update({where:{id:announcementId},data:{status:"PUBLISHED",approvedById:actor.userId,approvedAt:new Date(),publishedAt:new Date()}}); for(const e of a.offering.enrollments.filter((e:any)=>e.status==="ENROLLED")) await notifyOperational({userId:e.studentId,eventType:"CLASS_ANNOUNCEMENT_PUBLISHED",title:a.title,body:a.body.slice(0,180),link:`/student/classes/${a.offeringId}`,relatedEntityType:"CLASS_ANNOUNCEMENT",relatedEntityId:a.id,dedupeKey:`announcement:${a.id}:${e.studentId}`}); await auditOperationalEvent({actorUserId:actor.userId,action:"ANNOUNCEMENT_PUBLISHED",sourceType:"CLASS_ANNOUNCEMENT",sourceId:announcementId}); return row; }
export async function syncOperationalActionsForClass(offeringId:string, actorUserId="system"){ const ops=await (prisma as any).classOffering.findUnique({where:{id:offeringId},include:{template:true,sessions:{include:{attendance:true}},enrollments:true,guardianApprovalRequests:true,familyFormRequirements:true,familySupportRequests:true}}); if(!ops) return null; const lifecycle=deriveClassLifecycle(ops); if(!lifecycle.blocker) return null; const key=`CLASS:${offeringId}:${lifecycle.blocker.code}`; const lead=await actionLead(ops.chapterId); return (prisma as any).actionItem.upsert({where:{chapterId_operationalSourceKey:{chapterId:ops.chapterId,operationalSourceKey:key}},update:{status:"NOT_STARTED",title:lifecycle.blocker.label,leadId:lead,operationalIssueType:lifecycle.blocker.code},create:{title:lifecycle.blocker.label,description:`Synchronized blocker for ${ops.title}`,deadlineStart:nowPlus(3),leadId:lead,createdById:actorUserId,chapterId:ops.chapterId,relatedEntityType:"CLASS_OFFERING",relatedEntityId:offeringId,operationalSourceKey:key,operationalSourceType:"CLASS",operationalIssueType:lifecycle.blocker.code}}).catch(()=>null); }
export async function resolveOperationalAction(offeringId:string, issueType:string, actorUserId:string){ await (prisma as any).actionItem.updateMany({where:{relatedEntityType:"CLASS_OFFERING",relatedEntityId:offeringId,operationalIssueType:issueType,status:{not:"COMPLETE"}},data:{status:"COMPLETE",completedAt:new Date(),completionOutcome:"DELIVERED",completionNote:"Resolved by source mutation"}}).catch(()=>null); await auditOperationalEvent({actorUserId,action:"ACTION_SYNCHRONIZED_RESOLVED",sourceType:"CLASS_OFFERING",sourceId:offeringId,newState:{issueType}}); }
export async function persistBiweeklyActionPacket(actor:Session4Actor, chapterId:string, periodStart:Date, periodEnd:Date){ const packet=await (prisma as any).biweeklyActionPacket.upsert({where:{chapterId_periodStart_periodEnd:{chapterId,periodStart,periodEnd}},update:{state:"REFRESHED",generatedById:actor.userId,generatedAt:new Date()},create:{chapterId,periodStart,periodEnd,generatedById:actor.userId}}); const pipeline=await (prisma as any).classOffering.findMany({where:{chapterId},select:{id:true}}); for(const o of pipeline){ const action=await syncOperationalActionsForClass(o.id,actor.userId); if(action) await (prisma as any).biweeklyActionPacketItem.upsert({where:{packetId_sourceKey:{packetId:packet.id,sourceKey:action.operationalSourceKey}},update:{actionItemId:action.id,state:action.status==="COMPLETE"?"COMPLETE":"OPEN"},create:{packetId:packet.id,actionItemId:action.id,sourceKey:action.operationalSourceKey,ownerId:action.leadId,dueAt:action.deadlineStart}}); } return packet; }
export async function createImpactDecision(actor:Session4Actor, meetingId:string, input:any){ const decision=await (prisma as any).meetingDecision.create({data:{meetingId,decision:input.decision,rationale:input.rationale,decidedById:actor.userId}}); const action= input.ownerId ? await (prisma as any).actionItem.create({data:{title:input.actionTitle??input.decision,description:input.rationale,deadlineStart:input.dueAt??nowPlus(7),leadId:input.ownerId,createdById:actor.userId,meetingId,sourceType:"MEETING_DECISION",sourceId:decision.id,relatedEntityType:input.relatedEntityType,relatedEntityId:input.relatedEntityId,chapterId:input.chapterId}}) : null; await auditOperationalEvent({actorUserId:actor.userId,action:"IMPACT_DECISION_CREATED",sourceType:"MEETING",sourceId:meetingId,relatedEntityType:"ACTION_ITEM",relatedEntityId:action?.id,newState:input}); if(action) await notifyOperational({userId:input.ownerId,eventType:"MEETING_COMMITMENT_ASSIGNED",title:"Meeting commitment assigned",body:action.title,link:`/my-actions`,relatedEntityType:"ACTION_ITEM",relatedEntityId:action.id,dedupeKey:`meeting-action:${action.id}`,operational:true}); return {decision,action}; }
export async function createLeadershipIntervention(actor:Session4Actor,input:any){ if(!actor.roles.some(r=>["ADMIN","LEADERSHIP"].includes(r))) throw new Error("Leadership access required"); const row=await (prisma as any).leadershipIntervention.create({data:{chapterId:input.chapterId,actionItemId:input.actionItemId,sourceType:input.sourceType,sourceId:input.sourceId,createdById:actor.userId,ownerId:input.ownerId,severity:input.severity,note:input.note,meetingId:input.meetingId,dueAt:input.dueAt}}); if(input.actionItemId&&input.ownerId) await (prisma as any).actionItem.update({where:{id:input.actionItemId},data:{leadId:input.ownerId,deadlineStart:input.dueAt}}); await auditOperationalEvent({actorUserId:actor.userId,action:"LEADERSHIP_INTERVENTION_CREATED",sourceType:input.sourceType,sourceId:input.sourceId,newState:input}); return row; }
