import { getClassOperations } from "@/lib/class-lifecycle-service";
import { listEligibleInstructorCandidates } from "@/lib/session-4-operations";
import { announcementDraftAction, assignInstructorAction, enrollmentOperationAction, removeInstructorAction, supportTriageAction, syncActionsAction, waitlistDeclineAction, waitlistOfferAction } from "./session-4-actions";

function Submit({children}:{children:string}){return <button className="rounded bg-slate-900 px-3 py-2 text-sm font-semibold text-white" type="submit">{children}</button>}
export default async function ClassOpsPage({ params }: { params: Promise<{ classId: string }> }) {
 const { classId } = await params; const ops = await getClassOperations(classId); if (!ops) return <main className="p-6"><h1>Class operations</h1><p role="alert">Class not found or permission denied.</p></main>;
 const { offering, lifecycle } = ops; const candidates = await listEligibleInstructorCandidates(classId).catch(()=>[]);
 const assign = assignInstructorAction.bind(null,classId), remove = removeInstructorAction.bind(null,classId), enroll = enrollmentOperationAction.bind(null,classId), offer = waitlistOfferAction.bind(null,classId), decline = waitlistDeclineAction.bind(null,classId), triage = supportTriageAction.bind(null,classId), announce = announcementDraftAction.bind(null,classId), sync = syncActionsAction.bind(null,classId);
 return <main className="space-y-6 p-6"><header><p className="text-sm uppercase tracking-wide text-slate-500">Session 4 class operations</p><h1 className="text-3xl font-semibold">{offering.title}</h1><p className="mt-2 text-slate-700">{lifecycle.blocker?.label ?? lifecycle.nextAction}</p></header>
 <form action={sync}><Submit>Synchronize operational actions</Submit></form>
 <div className="grid gap-4 lg:grid-cols-2">
 <section className="rounded-2xl border p-4"><h2 className="font-semibold">Instructor assignment</h2><p>Current instructor: {offering.instructor?.name ?? "Needed"}</p><form action={assign} className="mt-3 space-y-2"><label className="block text-sm">Candidate<select name="instructorId" className="mt-1 w-full rounded border p-2">{candidates.map((c:any)=><option key={c.id} value={c.id}>{c.name} — {c.readiness.ready?"ready":c.readiness.missing.join(", ")}</option>)}</select></label><label className="block text-sm">Reason<input name="reason" required className="mt-1 w-full rounded border p-2" /></label><label className="flex gap-2 text-sm"><input name="overrideReadiness" type="checkbox"/> Staff readiness override</label><Submit>{offering.instructorId?"Reassign instructor":"Assign instructor"}</Submit></form><form action={remove} className="mt-3 flex gap-2"><input name="reason" aria-label="Removal reason" placeholder="Removal reason" required className="flex-1 rounded border p-2"/><Submit>Remove instructor</Submit></form></section>
 <section className="rounded-2xl border p-4"><h2 className="font-semibold">Enrollment operations</h2><p>{lifecycle.counts.enrolled}/{offering.capacity} seats admitted. Enrollment is {offering.enrollmentOpen?"open":"closed"}.</p><form action={enroll} className="mt-3 grid gap-2"><input name="capacity" type="number" min={lifecycle.counts.enrolled} placeholder="New capacity" className="rounded border p-2"/><select name="enrollmentOpen" className="rounded border p-2"><option value="">Leave enrollment state</option><option value="true">Open enrollment</option><option value="false">Close enrollment</option></select><input name="studentId" placeholder="Student ID for staff placement" className="rounded border p-2"/><input name="removeEnrollmentId" placeholder="Enrollment ID to drop safely" className="rounded border p-2"/><input name="reason" required placeholder="Audit reason" className="rounded border p-2"/><Submit>Apply enrollment operation</Submit></form></section>
 <section className="rounded-2xl border p-4"><h2 className="font-semibold">Waitlist offers</h2>{offering.familyWaitlistEntries?.length? offering.familyWaitlistEntries.map((w:any)=><div key={w.id} className="border-t py-2"><p>{w.studentUserId}: {w.status} {w.offerExpiresAt?`until ${new Date(w.offerExpiresAt).toLocaleString()}`:""}</p><form action={offer} className="flex gap-2"><input type="hidden" name="waitlistId" value={w.id}/><input name="expiresAt" type="datetime-local" required className="rounded border p-2"/><input name="note" placeholder="Offer note" className="rounded border p-2"/><Submit>Create offer</Submit></form><form action={decline} className="mt-2 flex gap-2"><input type="hidden" name="waitlistId" value={w.id}/><input name="note" placeholder="Decline/withdraw note" className="rounded border p-2"/><Submit>Decline offer</Submit></form></div>):<p>No active waitlist entries.</p>}</section>
 <section className="rounded-2xl border p-4"><h2 className="font-semibold">Support triage</h2>{offering.familySupportRequests?.length? offering.familySupportRequests.map((r:any)=><form action={triage} key={r.id} className="space-y-2 border-t py-2"><input type="hidden" name="requestId" value={r.id}/><p>{r.category}: {r.externalStatus}</p><input name="ownerId" placeholder="Owner user ID" className="w-full rounded border p-2"/><select name="status" className="w-full rounded border p-2"><option>REVIEWING</option><option>NEED_MORE_INFORMATION</option><option>RESOLVED</option><option>CLOSED</option></select><input name="severity" placeholder="Severity" className="w-full rounded border p-2"/><textarea name="internalComment" placeholder="Internal note (never family-visible)" className="w-full rounded border p-2"/><textarea name="familyResponse" placeholder="Family-visible response" className="w-full rounded border p-2"/><Submit>Update support request</Submit></form>):<p>No support requests.</p>}</section>
 <section className="rounded-2xl border p-4"><h2 className="font-semibold">Announcement draft and publish</h2><form action={announce} className="grid gap-2"><input name="title" required placeholder="Title" className="rounded border p-2"/><select name="announcementType" className="rounded border p-2"><option>CLASS_REMINDER</option><option>PREPARATION_NOTE</option><option>SCHEDULE_CHANGE</option><option>CANCELLATION</option><option>LOCATION_CHANGE</option><option>JOIN_LINK_UPDATE</option><option>INSTRUCTOR_CHANGE</option></select><select name="audience" className="rounded border p-2"><option>ADMITTED_FAMILIES</option><option>INSTRUCTORS</option></select><textarea name="body" required placeholder="Message" className="rounded border p-2"/><label className="flex gap-2 text-sm"><input name="publish" type="checkbox"/> Publish immediately when authorized</label><Submit>Save announcement</Submit></form></section>
 <section className="rounded-2xl border p-4"><h2 className="font-semibold">Audit timeline</h2>{offering.timeline?.length? <ul>{offering.timeline.map((t:any)=><li key={t.id} className="border-t py-2"><b>{t.kind}</b> {t.summary}<br/><span className="text-xs text-slate-500">{new Date(t.createdAt).toLocaleString()}</span></li>)}</ul>:<p>No audit events yet.</p>}</section>
 </div></main>; }
