"use server";
import { revalidatePath } from "next/cache";
import { getSession } from "@/lib/auth-supabase";
import { assignInstructor, createWaitlistOffer, declineWaitlistOffer, publishAnnouncement, recordAttendance, removeInstructor, syncOperationalActionsForClass, triageSupportRequest, updateEnrollmentOperations, updateSessionReadiness, upsertAnnouncement } from "@/lib/session-4-operations";
async function actor(){ const s=await getSession(); if(!s?.user?.id) throw new Error("Unauthorized"); return { userId:s.user.id, roles:s.user.roles??[] }; }
function str(fd:FormData,k:string){ return String(fd.get(k)??"").trim(); }
export async function assignInstructorAction(classId:string, fd:FormData){ await assignInstructor(await actor(), classId, str(fd,"instructorId"), str(fd,"reason"), fd.get("overrideReadiness")==="on"); revalidatePath(`/chapter/classes/${classId}`); }
export async function removeInstructorAction(classId:string, fd:FormData){ await removeInstructor(await actor(), classId, str(fd,"reason")); revalidatePath(`/chapter/classes/${classId}`); }
export async function enrollmentOperationAction(classId:string, fd:FormData){ await updateEnrollmentOperations(await actor(), classId, { enrollmentOpen: fd.has("enrollmentOpen") ? fd.get("enrollmentOpen")==="true" : undefined, capacity: str(fd,"capacity") ? Number(str(fd,"capacity")) : undefined, studentId: str(fd,"studentId") || undefined, removeEnrollmentId: str(fd,"removeEnrollmentId") || undefined, reason: str(fd,"reason") }); revalidatePath(`/chapter/classes/${classId}`); }
export async function waitlistOfferAction(classId:string, fd:FormData){ await createWaitlistOffer(await actor(), str(fd,"waitlistId"), new Date(str(fd,"expiresAt")), str(fd,"note")); revalidatePath(`/chapter/classes/${classId}`); }
export async function waitlistDeclineAction(classId:string, fd:FormData){ await declineWaitlistOffer(await actor(), str(fd,"waitlistId"), str(fd,"note")); revalidatePath(`/chapter/classes/${classId}`); }
export async function supportTriageAction(classId:string, fd:FormData){ await triageSupportRequest(await actor(), str(fd,"requestId"), { ownerId:str(fd,"ownerId")||undefined, team:str(fd,"team")||undefined, category:str(fd,"category")||undefined, severity:str(fd,"severity")||undefined, status:str(fd,"status"), note:str(fd,"note"), internalComment:str(fd,"internalComment"), familyResponse:str(fd,"familyResponse"), safety:fd.get("safety")==="on" }); revalidatePath(`/chapter/classes/${classId}`); }
export async function announcementDraftAction(classId:string, fd:FormData){ const row=await upsertAnnouncement(await actor(), classId, { id:str(fd,"announcementId")||undefined,title:str(fd,"title"),body:str(fd,"body"),announcementType:str(fd,"announcementType"),audience:str(fd,"audience"),status:"DRAFT" }); if(fd.get("publish")==="on") await publishAnnouncement(await actor(), row.id); revalidatePath(`/chapter/classes/${classId}`); }
export async function syncActionsAction(classId:string){ await syncOperationalActionsForClass(classId); revalidatePath(`/chapter/classes/${classId}`); }
export async function attendanceAction(classId:string, fd:FormData){ await recordAttendance(await actor(), str(fd,"sessionId"), JSON.parse(str(fd,"records"))); revalidatePath(`/chapter/classes/${classId}`); }
export async function readinessAction(classId:string, fd:FormData){ await updateSessionReadiness(await actor(), str(fd,"sessionId"), { note:str(fd,"note"), lessonReviewed:fd.get("lessonReviewed")==="on", materialsReviewed:fd.get("materialsReviewed")==="on", studentContextReviewed:fd.get("studentContextReviewed")==="on", confirmReady:fd.get("confirmReady")==="on" }); revalidatePath(`/chapter/classes/${classId}`); }
