import Link from "next/link";
import { redirect } from "next/navigation";

import { ButtonLink, PageHeaderV2 } from "@/components/ui-v2";
import { getChapterViewerContext } from "@/lib/chapters/access";
import { loadChapterOperations } from "@/lib/chapters/operations";
import { ChapterClassCharts, ChapterTaskTrendChart } from "@/components/chapters/chapter-operations-charts";

export const dynamic = "force-dynamic";
export const metadata = { title: "Chapter Activity — Pathways Portal" };

export default async function ChapterActivityPage() {
  const ctx = await getChapterViewerContext();
  if (!ctx.ledChapterId) redirect(ctx.isLeadership ? "/admin/chapters" : "/chapter");
  const data = await loadChapterOperations(ctx.ledChapterId);
  if (!data) redirect("/chapter");
  const totalCapacity = data.classes.reduce((sum, c) => sum + c.capacity, 0);
  const totalEnrolled = data.classes.reduce((sum, c) => sum + c.enrolled, 0);
  const utilization = totalCapacity ? Math.round((totalEnrolled / totalCapacity) * 100) : 0;

  return <main className="mx-auto w-full max-w-6xl px-6 py-8"><PageHeaderV2 eyebrow="Chapter Operations" title="Operational activity" subtitle="Classes, sessions, outreach, attendance, capacity, and task execution from the underlying portal records." actions={<ButtonLink href="/chapter" variant="secondary" size="sm">Back to overview</ButtonLink>} />
    <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-base font-semibold text-slate-950">Programming and capacity</h2><p className="mt-1 text-sm text-slate-600">{totalEnrolled} enrolled across {totalCapacity} seats · {utilization}% utilized · {data.classes.filter((c) => c.enrolled < c.capacity * 0.5).length} underfilled</p></div><Link href="/admin/classes" className="text-sm font-medium text-brand-700">Manage classes</Link></div>{data.classes.length ? <><div className="mt-4"><ChapterClassCharts data={data.classes} /></div><div className="mt-4 overflow-x-auto"><table className="w-full border-y border-slate-200 text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-2">Class</th><th className="px-3 py-2 text-right">Enrolled</th><th className="px-3 py-2 text-right">Capacity</th><th className="px-3 py-2 text-right">Utilization</th><th className="px-3 py-2 text-right">Attendance</th></tr></thead><tbody>{data.classes.map((c) => <tr key={c.id} className="border-t border-slate-100"><td className="px-3 py-2"><Link href={c.href} className="font-medium text-brand-700">{c.name}</Link></td><td className="px-3 py-2 text-right">{c.enrolled}</td><td className="px-3 py-2 text-right">{c.capacity}</td><td className="px-3 py-2 text-right">{c.capacity ? Math.round((c.enrolled / c.capacity) * 100) : 0}%</td><td className="px-3 py-2 text-right">{c.attendance}%</td></tr>)}</tbody></table></div></> : <p className="mt-4 border-y border-slate-200 py-6 text-sm text-slate-600">No chapter classes have been created.</p>}</section>
    <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-base font-semibold text-slate-950">Class sessions</h2><p className="mt-1 text-sm text-slate-600">Attendance is calculated from each session’s student attendance records.</p></div><Link href="/admin/classes" className="text-sm font-medium text-brand-700">Manage programming</Link></div>{data.sessionLog.length ? <div className="mt-4 overflow-x-auto"><table className="w-full border-y border-slate-200 text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-2">Date</th><th className="px-3 py-2">Class / topic</th><th className="px-3 py-2">Instructor</th><th className="px-3 py-2 text-right">Enrolled</th><th className="px-3 py-2 text-right">Attended</th><th className="px-3 py-2 text-right">Rate</th><th className="px-3 py-2">Follow-up</th></tr></thead><tbody>{data.sessionLog.map((s) => <tr key={s.id} className="border-t border-slate-100 align-top"><td className="whitespace-nowrap px-3 py-2">{new Date(s.dateISO).toLocaleDateString()}</td><td className="px-3 py-2"><Link href={s.href} className="font-medium text-brand-700">{s.className}</Link><p className="text-xs text-slate-500">{s.topic}</p></td><td className="px-3 py-2"><Link href={`/chapter/instructors/${s.instructorId}`} className="text-brand-700">{s.instructorName}</Link></td><td className="px-3 py-2 text-right tabular-nums">{s.enrolled}</td><td className="px-3 py-2 text-right tabular-nums">{s.attended}</td><td className="px-3 py-2 text-right tabular-nums">{s.attendanceRate}%</td><td className="max-w-xs px-3 py-2 text-slate-600">{s.needsFollowUp ? s.followUpReason : "Clear"}</td></tr>)}</tbody></table></div> : <p className="mt-4 border-y border-slate-200 py-6 text-sm text-slate-600">No class sessions have been recorded.</p>}</section>

    <section className="mt-10"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-base font-semibold text-slate-950">Partner outreach</h2><p className="mt-1 text-sm text-slate-600">Every row comes from the partner relationship timeline; follow-up dates are not entered again here.</p></div><Link href="/partners" className="text-sm font-medium text-brand-700">Open partner pipeline</Link></div>{data.outreachLog.length ? <div className="mt-4 overflow-x-auto"><table className="w-full border-y border-slate-200 text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-2">Date</th><th className="px-3 py-2">Partner</th><th className="px-3 py-2">Type / result</th><th className="px-3 py-2">Owner</th><th className="px-3 py-2">Next follow-up</th></tr></thead><tbody>{data.outreachLog.map((o) => <tr key={o.id} className="border-t border-slate-100 align-top"><td className="whitespace-nowrap px-3 py-2">{new Date(o.dateISO).toLocaleDateString()}</td><td className="px-3 py-2"><Link href={o.href} className="font-medium text-brand-700">{o.partnerName}</Link></td><td className="max-w-md px-3 py-2"><span className="text-xs font-medium text-slate-500">{o.kind.replaceAll("_", " ")}</span><p className="mt-1 text-slate-700">{o.result}</p></td><td className="px-3 py-2 text-slate-600">{o.owner}</td><td className="whitespace-nowrap px-3 py-2 text-slate-600">{o.nextFollowUpISO ? new Date(o.nextFollowUpISO).toLocaleDateString() : "Not scheduled"}</td></tr>)}</tbody></table></div> : <p className="mt-4 border-y border-slate-200 py-6 text-sm text-slate-600">No partner outreach has been logged in the last eight weeks.</p>}</section>
    <section id="task-execution" className="mt-10 border-t border-slate-200 pt-4"><h2 className="text-base font-semibold text-slate-950">Task execution</h2><p className="mb-3 mt-1 text-sm text-slate-600">Tasks created and completed by week. Open, overdue, and blocked work remains in the Actions lane.</p><ChapterTaskTrendChart data={data.activityTrend} /></section>
  </main>;
}
