import { prisma } from "@/lib/prisma";
import { expireWaitlistOffers, persistBiweeklyActionPacket, syncOperationalActionsForClass } from "@/lib/session-4-operations";

async function main() {
  if (process.env.NODE_ENV === "production" || process.env.YPP_ALLOW_SESSION4_QA_SEED !== "true") throw new Error("Refusing to seed Session 4 QA data without YPP_ALLOW_SESSION4_QA_SEED=true outside production.");
  const chapter = await (prisma as any).chapter.upsert({ where: { slug: "session-4-qa" }, update: {}, create: { name: "Session 4 QA Chapter", slug: "session-4-qa" } });
  const upsertUser = (email:string, name:string, role:string) => (prisma as any).user.upsert({ where:{email}, update:{name}, create:{email,name,roles:{create:{role}}} });
  const [president, leader, safety, instructor, instructor2, guardian, guardian2, student, student2] = await Promise.all([
    upsertUser("s4-president@ypp.test","S4 Chapter President","CHAPTER_PRESIDENT"), upsertUser("s4-leader@ypp.test","S4 Leadership","ADMIN"), upsertUser("s4-safety@ypp.test","S4 Safety Staff","STAFF"), upsertUser("s4-instructor@ypp.test","S4 Ready Instructor","INSTRUCTOR"), upsertUser("s4-instructor2@ypp.test","S4 Backup Instructor","INSTRUCTOR"), upsertUser("s4-guardian@ypp.test","S4 Guardian","PARENT"), upsertUser("s4-guardian2@ypp.test","S4 Second Guardian","PARENT"), upsertUser("s4-student@ypp.test","S4 Student","STUDENT"), upsertUser("s4-student2@ypp.test","S4 Waitlisted Student","STUDENT"),
  ]);
  await (prisma as any).instructorApplication.upsert({ where:{ userId: instructor.id }, update:{ status:"APPROVED" }, create:{ userId: instructor.id, status:"APPROVED" } }).catch(()=>null);
  const template = await (prisma as any).classTemplate.upsert({ where:{ id:"session-4-template" }, update:{}, create:{ id:"session-4-template", title:"Session 4 Operations Lab", description:"QA", interestArea:"Technology", prerequisites:[], learningOutcomes:["Operate"], createdById: president.id } });
  const cls = await (prisma as any).classOffering.upsert({ where:{ id:"session-4-active-class" }, update:{ chapterId:chapter.id, instructorId: instructor.id }, create:{ id:"session-4-active-class", templateId:template.id, instructorId: instructor.id, title:"Session 4 Active Class", startDate:new Date(), endDate:new Date(Date.now()+14*864e5), meetingDays:["Tuesday"], meetingTime:"16:00-17:00", capacity:1, status:"PUBLISHED", chapterId:chapter.id } });
  const vacant = await (prisma as any).classOffering.upsert({ where:{ id:"session-4-vacant-class" }, update:{ chapterId:chapter.id, instructorId:null }, create:{ id:"session-4-vacant-class", templateId:template.id, instructorId: null, title:"Session 4 Needs Instructor", startDate:new Date(), endDate:new Date(Date.now()+14*864e5), meetingDays:["Thursday"], meetingTime:"16:00-17:00", capacity:3, status:"PUBLISHED", chapterId:chapter.id } });
  await (prisma as any).familyEnrollmentConfig.upsert({ where:{offeringId:cls.id}, update:{requiresGuardianApproval:true}, create:{offeringId:cls.id,mode:"GUARDIAN_APPROVAL",requiresGuardianApproval:true} });
  await (prisma as any).classSession.upsert({ where:{ offeringId_sessionNumber:{offeringId:cls.id,sessionNumber:1}}, update:{}, create:{ offeringId:cls.id,sessionNumber:1,date:new Date(Date.now()+864e5),startTime:"16:00",endTime:"17:00",topic:"Launch",learningOutcomes:[] } });
  await (prisma as any).classEnrollment.upsert({ where:{ studentId_offeringId:{studentId:student.id,offeringId:cls.id}}, update:{status:"ENROLLED"}, create:{studentId:student.id,offeringId:cls.id,status:"ENROLLED",outcomesAchieved:[]} });
  await (prisma as any).classEnrollment.upsert({ where:{ studentId_offeringId:{studentId:student2.id,offeringId:cls.id}}, update:{status:"WAITLISTED"}, create:{studentId:student2.id,offeringId:cls.id,status:"WAITLISTED",outcomesAchieved:[]} });
  await (prisma as any).familyWaitlistEntry.upsert({ where:{ studentUserId_offeringId:{studentUserId:student2.id,offeringId:cls.id}}, update:{status:"OFFERED",offerExpiresAt:new Date(Date.now()+864e5)}, create:{studentUserId:student2.id,offeringId:cls.id,status:"OFFERED",offerExpiresAt:new Date(Date.now()+864e5),createdById:guardian.id} });
  await (prisma as any).guardianApprovalRequest.upsert({ where:{ studentUserId_offeringId_status:{studentUserId:student2.id,offeringId:cls.id,status:"PENDING"}}, update:{guardianUserId:guardian2.id}, create:{studentUserId:student2.id,guardianUserId:guardian2.id,offeringId:cls.id,requestedById:student2.id,status:"PENDING"} }).catch(()=>null);
  const form = await (prisma as any).familyFormTemplate.upsert({ where:{key:"session-4-consent"}, update:{}, create:{key:"session-4-consent",title:"Session 4 Consent",formType:"CONSENT"} });
  const version = await (prisma as any).familyFormVersion.upsert({ where:{ templateId_version:{templateId:form.id,version:1}}, update:{}, create:{templateId:form.id,version:1,content:{fields:[{type:"signature_acknowledgement",label:"I agree"}]}} });
  const req = await (prisma as any).familyFormRequirement.create({ data:{versionId:version.id,studentUserId:student.id,offeringId:cls.id,reason:"QA consent",staffReviewRequired:true,blocksAttendance:true} }).catch(()=>null);
  await (prisma as any).familySupportRequest.create({ data:{requesterUserId:guardian.id,requesterRole:"GUARDIAN",studentUserId:student.id,guardianUserId:guardian.id,offeringId:cls.id,category:"SCHEDULE",description:"Need help",externalStatus:"REVIEWING",internalOwnerId:president.id} }).catch(()=>null);
  await (prisma as any).classAnnouncement.create({ data:{offeringId:cls.id,authorId:president.id,title:"Published QA update",body:"Visible to admitted families",status:"PUBLISHED",publishedAt:new Date()} }).catch(()=>null);
  await syncOperationalActionsForClass(vacant.id, president.id); await persistBiweeklyActionPacket({userId:president.id,roles:["CHAPTER_PRESIDENT"]}, chapter.id, new Date("2026-07-01"), new Date("2026-07-14")); await expireWaitlistOffers();
  console.log({ chapter: chapter.id, president: president.email, leader: leader.email, safety: safety.email, instructor: instructor.email, instructor2: instructor2.email, guardian: guardian.email, student: student.email, classes: [cls.id, vacant.id], requirement: req?.id });
}
main().finally(()=>prisma.$disconnect());
