-- Migration: live_interview_runner
-- Adds live during-interview state, richer question guidance, and guided notes.

DO $$
BEGIN
  CREATE TYPE "InterviewQuestionRunStatus" AS ENUM ('UNTOUCHED', 'ASKED', 'SKIPPED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE "InterviewAnswerTag" AS ENUM (
    'STRONG_ANSWER',
    'WEAK_ANSWER',
    'RED_FLAG',
    'FOLLOW_UP_NEEDED',
    'GREAT_COMMUNICATOR',
    'HIGH_POTENTIAL',
    'NEEDS_COACHING'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "InstructorInterviewQuestionBank"
  ADD COLUMN IF NOT EXISTS "competency" TEXT,
  ADD COLUMN IF NOT EXISTS "whyItMatters" TEXT,
  ADD COLUMN IF NOT EXISTS "interviewerGuidance" TEXT,
  ADD COLUMN IF NOT EXISTS "listenFor" TEXT,
  ADD COLUMN IF NOT EXISTS "suggestedFollowUps" JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "strongSignals" JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "concernSignals" JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "notePrompts" JSONB NOT NULL DEFAULT '[]';

ALTER TABLE "InstructorInterviewReview"
  ADD COLUMN IF NOT EXISTS "demeanorNotes" TEXT,
  ADD COLUMN IF NOT EXISTS "maturityNotes" TEXT,
  ADD COLUMN IF NOT EXISTS "communicationNotes" TEXT,
  ADD COLUMN IF NOT EXISTS "professionalismNotes" TEXT,
  ADD COLUMN IF NOT EXISTS "followUpItems" TEXT;

ALTER TABLE "InstructorInterviewQuestionResponse"
  ADD COLUMN IF NOT EXISTS "status" "InterviewQuestionRunStatus" NOT NULL DEFAULT 'UNTOUCHED',
  ADD COLUMN IF NOT EXISTS "competency" TEXT,
  ADD COLUMN IF NOT EXISTS "whyAsked" TEXT,
  ADD COLUMN IF NOT EXISTS "rating" "ProgressStatus",
  ADD COLUMN IF NOT EXISTS "tags" "InterviewAnswerTag"[] NOT NULL DEFAULT ARRAY[]::"InterviewAnswerTag"[],
  ADD COLUMN IF NOT EXISTS "askedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "skippedAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "InstructorInterviewQuestionResponse_reviewId_status_idx"
  ON "InstructorInterviewQuestionResponse"("reviewId", "status");

INSERT INTO "InstructorInterviewQuestionBank" (
  "id",
  "slug",
  "prompt",
  "helperText",
  "followUpPrompt",
  "topic",
  "competency",
  "whyItMatters",
  "interviewerGuidance",
  "listenFor",
  "suggestedFollowUps",
  "strongSignals",
  "concernSignals",
  "notePrompts",
  "sortOrder",
  "isActive",
  "createdAt",
  "updatedAt"
)
VALUES
  (
    'iqb_motivation',
    'motivation_for_applying',
    'What drew you to teaching through YPP, and what do you hope students walk away with after your class?',
    'Tests authentic motivation, student-centered purpose, and whether the candidate understands YPP as more than a resume line.',
    'What would make this class feel meaningful for students in your chapter?',
    'Motivation & Fit',
    'Authentic motivation',
    'A strong instructor needs a clear reason for teaching that centers students, not just personal accomplishment.',
    'Invite a concrete story. Listen for whether they talk about students, access, confidence, curiosity, or community impact.',
    'Student-centered language, clear personal connection, realistic expectations, and an understanding of YPP values.',
    '["What personal experience makes this topic matter to you?","How would you explain YPP to a family considering your class?","What part of teaching this would still matter to you if it was hard?"]'::jsonb,
    '["Names a real student benefit beyond exposure","Shows humility and service orientation","Connects passion to chapter/community needs"]'::jsonb,
    '["Mostly talks about resume value or prestige","Cannot explain why YPP specifically fits","Motivation sounds vague or externally driven"]'::jsonb,
    '["Why YPP?","Student impact they named","Personal connection","Any self-serving or unclear motive"]'::jsonb,
    1,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_subject',
    'passion_for_subject',
    'What makes your topic exciting enough that students would want to keep showing up for it week after week?',
    'Tests real passion and the ability to translate subject matter into student curiosity.',
    'What part of this topic do you think students will care about most?',
    'Subject Expertise',
    'Passion and student relevance',
    'Students respond to instructors who can make a subject feel alive, approachable, and worth returning to.',
    'Push for specificity. The best answers describe moments, problems, examples, or projects students can actually experience.',
    'Concrete examples, contagious enthusiasm, student-facing hooks, and awareness of what beginners find interesting.',
    '["What is one activity or example you would use in the first session?","What is a common misconception students might have about this topic?","How would you make this topic accessible to a younger student?"]'::jsonb,
    '["Can explain the subject without jargon","Identifies a compelling student hook","Shows sustained personal curiosity"]'::jsonb,
    '["Only describes the topic in academic terms","Cannot name what students would do or make","Interest feels shallow or performative"]'::jsonb,
    '["Subject hook","Evidence of real passion","Beginner-friendly framing","Potential class activity"]'::jsonb,
    2,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_subject_depth',
    'subject_depth',
    'Tell me about a concept, tool, or skill in your topic that you know well. How would you decide whether it belongs in this class?',
    'Tests subject knowledge, curriculum judgment, and ability to choose teachable scope.',
    'What would you leave out, even if you personally find it interesting?',
    'Subject Expertise',
    'Subject knowledge and scope judgment',
    'Depth matters, but instructors also need restraint so students are not overloaded.',
    'Look for real expertise paired with age-appropriate filtering. Strong candidates can separate what is impressive from what is teachable.',
    'Accurate subject explanation, clear prerequisites, thoughtful scope, and awareness of student readiness.',
    '["How would you check whether students are ready for that concept?","What prerequisite knowledge would they need?","What would a successful beginner-level version look like?"]'::jsonb,
    '["Explains the concept clearly and accurately","Makes smart tradeoffs about depth","Can identify prerequisite skills"]'::jsonb,
    '["Overloads the class with advanced material","Cannot simplify without losing accuracy","Seems unsure about the subject itself"]'::jsonb,
    '["Depth evidence","Scope decision","Prerequisites","What they would omit"]'::jsonb,
    3,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_structure',
    'class_structure',
    'Walk me through your class from the first session to the final outcome. How do students build skill or confidence over time?',
    'Tests course structure, sequencing, feasibility, and curriculum readiness.',
    'Where do you expect students to struggle, and how would you support them?',
    'Teaching & Curriculum',
    'Curriculum readiness',
    'A good idea only works if the instructor can turn it into a realistic learning path.',
    'Ask them to be concrete about the beginning, middle, and end. Listen for progression rather than a list of disconnected activities.',
    'Clear sequence, realistic pacing, meaningful student outcome, and support for predictable sticking points.',
    '["What would students do in week one?","What would the final project or outcome be?","What would you cut if time ran short?"]'::jsonb,
    '["Describes a coherent learning arc","Names checkpoints or milestones","Connects activities to outcomes"]'::jsonb,
    '["Plan is too broad for the available time","Cannot explain how sessions connect","No clear student outcome"]'::jsonb,
    '["Opening session","Skill progression","Final outcome","Pacing risks"]'::jsonb,
    4,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_teach',
    'teach_in_60_seconds',
    'Teach me one concept from your class in about 60 seconds, as if I were a student hearing it for the first time.',
    'Tests live teaching clarity, pacing, warmth, and ability to translate expertise.',
    'What would you do next if students looked confused after that explanation?',
    'Teaching & Curriculum',
    'Teaching clarity',
    'The interview needs at least one real teaching sample, not just claims about teaching.',
    'Let them teach without interrupting. Notice structure, examples, tone, and whether they check for understanding.',
    'Simple framing, clear example, natural pacing, warmth, and an adjustment plan for confusion.',
    '["How would you check whether students understood?","Can you explain the same idea using a different example?","What question would you ask students right after teaching that?"]'::jsonb,
    '["Makes a hard idea feel approachable","Uses examples instead of jargon","Responds calmly to confusion"]'::jsonb,
    '["Rambles or over-explains","Uses unexplained jargon","Shows frustration or rigidity when asked to adapt"]'::jsonb,
    '["Clarity","Pacing","Student check","Adaptation when confused"]'::jsonb,
    5,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_experience',
    'prior_teaching_experience',
    'What teaching, tutoring, mentoring, coaching, or facilitation experience has prepared you for this role?',
    'Tests whether they have practiced leading others and what they learned from it.',
    'What did that experience teach you about working with students who learn differently?',
    'Teaching & Curriculum',
    'Teaching experience and reflection',
    'Prior experience is useful when the candidate can reflect on what worked, what did not, and how they adapted.',
    'Experience can be formal or informal. Focus less on title and more on lessons learned and maturity.',
    'Specific examples, adaptation, student empathy, and honest reflection.',
    '["Tell me about a time an explanation did not land.","How did you adjust for a student who needed more support?","What feedback have you received as a teacher or mentor?"]'::jsonb,
    '["Reflects honestly on past teaching","Shows patience with different readiness levels","Can name concrete adjustments"]'::jsonb,
    '["Has experience but little reflection","Blames students for not understanding","Cannot describe adapting their approach"]'::jsonb,
    '["Relevant experience","Adaptation example","Reflection quality","Student empathy"]'::jsonb,
    6,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_curriculum_adaptation',
    'curriculum_adaptation',
    'If your first class plan is not working in the moment, how would you decide what to adjust while still keeping the class on track?',
    'Tests adaptability, classroom judgment, and ability to support students without abandoning goals.',
    'What signs would tell you students need a different explanation, activity, or pace?',
    'Situational Judgment',
    'Adaptability',
    'Live classes rarely go exactly as planned. Instructors need calm adjustment habits.',
    'Listen for practical observation and adjustment, not vague flexibility. Strong candidates keep student outcomes in view.',
    'Noticing confusion, simplifying, changing modality, checking understanding, and preserving the main objective.',
    '["What would you do if an activity took twice as long as expected?","How would you handle one student racing ahead while others are stuck?","What would you prepare ahead of time to make adaptation easier?"]'::jsonb,
    '["Uses student evidence to adapt","Keeps the goal clear while changing method","Stays calm and practical"]'::jsonb,
    '["Says they would just push through","Has no backup plan","Treats adaptation as lowering standards"]'::jsonb,
    '["Adjustment trigger","Backup strategy","How they keep standards","Student evidence used"]'::jsonb,
    7,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_student',
    'student_scenario',
    'How would you respond if a student seemed disengaged, discouraged, or far behind the rest of the class?',
    'Tests student support mindset, maturity, warmth, and practical intervention.',
    'How would you keep standards high while still supporting that student?',
    'Situational Judgment',
    'Student support mindset',
    'YPP instructors need to support students with empathy while preserving a meaningful learning environment.',
    'Look for curiosity before judgment. Strong answers include private check-ins, small wins, and communication when needed.',
    'Warmth, practical support, respect for the student, and appropriate escalation if the concern continues.',
    '["What would you say to the student privately?","When would you involve a parent or chapter lead?","How would you prevent the student from feeling singled out?"]'::jsonb,
    '["Starts with curiosity and encouragement","Breaks the task into manageable steps","Knows when to ask for help"]'::jsonb,
    '["Labels the student as lazy","Ignores the concern","Only offers generic encouragement with no plan"]'::jsonb,
    '["Student support plan","Tone/maturity","Escalation judgment","High standards with care"]'::jsonb,
    8,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_parent',
    'parent_scenario',
    'How would you handle a parent who is worried that your class feels disorganized or is not meeting expectations?',
    'Tests parent communication, professionalism, ownership, and follow-through.',
    'What would you say, and what follow-up would you make sure happened next?',
    'Communication',
    'Parent communication maturity',
    'Parents need to trust that instructors respond clearly, calmly, and responsibly.',
    'Listen for ownership without defensiveness. Strong candidates acknowledge the concern, clarify facts, and propose follow-up.',
    'Calm tone, accountability, specific next step, and willingness to involve chapter leadership when appropriate.',
    '["How would you respond if the parent sounded frustrated?","What details would you document after that conversation?","When would you loop in a chapter lead?"]'::jsonb,
    '["Acknowledges concern without arguing","Offers a concrete follow-up","Communicates professionally and promptly"]'::jsonb,
    '["Gets defensive","Blames the parent or student","Promises vague improvement without specifics"]'::jsonb,
    '["Opening response","Ownership","Follow-up plan","Escalation judgment"]'::jsonb,
    9,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_commitment',
    'time_commitment',
    'What else is on your plate this season, and how will you make sure you can stay prepared, responsive, and consistent if you teach with YPP?',
    'Tests reliability, time commitment, planning habits, and realistic self-awareness.',
    'What would your weekly preparation and communication routine look like?',
    'Reliability & Time Commitment',
    'Reliability and time commitment',
    'A passionate candidate still needs enough capacity and habits to run a dependable class.',
    'Ask for a real weekly plan. Listen for concrete schedule management, not just confidence.',
    'Specific availability, planning routine, communication norms, and awareness of conflicts.',
    '["What would make this commitment hard to keep?","How far ahead would you prepare each session?","What would you do if school or exams became intense?"]'::jsonb,
    '["Names real constraints honestly","Has a specific preparation routine","Understands responsiveness expectations"]'::jsonb,
    '["Overcommitted with no plan","Dismisses preparation time","Gives unrealistic availability"]'::jsonb,
    '["Time constraints","Prep routine","Communication habits","Risk of overcommitment"]'::jsonb,
    10,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_professionalism_followthrough',
    'professionalism_followthrough',
    'Tell me about a time you had to follow through on something important even when it became inconvenient. What did you do?',
    'Tests professionalism, ownership, and follow-through under pressure.',
    'What would you do if you realized you were going to miss a YPP deadline or commitment?',
    'Reliability & Time Commitment',
    'Professionalism and follow-through',
    'Instructors represent YPP to students and families, so reliability under pressure matters.',
    'Look for a real example, not perfection. Strong candidates communicate early, own the impact, and repair trust.',
    'Early communication, responsibility, practical repair, and learning from the situation.',
    '["What did you learn from that situation?","How did you communicate with people depending on you?","What systems do you use now to avoid that happening again?"]'::jsonb,
    '["Owns mistakes without excuses","Communicates early","Uses systems to follow through"]'::jsonb,
    '["Blames others or circumstances","Waits until the last minute to communicate","No evidence of changed habits"]'::jsonb,
    '["Example quality","Ownership","Communication timing","Systems/habits"]'::jsonb,
    11,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_community',
    'community_fit',
    'How do you see yourself contributing to the YPP community beyond teaching one class?',
    'Tests chapter-mindedness, collaboration, community fit, and leadership potential.',
    'How would you build trust with families, students, and other chapter leaders?',
    'Leadership & Community',
    'Community fit and leadership upside',
    'YPP works best when instructors see themselves as part of a community, not isolated class owners.',
    'Listen for realistic contribution, collaboration, and service. Leadership potential can be quiet and practical.',
    'Willingness to collaborate, support peers, communicate with chapter leaders, and contribute to community energy.',
    '["What kind of chapter support would help you succeed?","How would you support another instructor?","What role could you imagine growing into over time?"]'::jsonb,
    '["Shows chapter-mindedness","Names practical ways to contribute","Has collaborative instincts"]'::jsonb,
    '["Only interested in their own class","Dismisses coordination with others","No interest in community responsibilities"]'::jsonb,
    '["Contribution beyond class","Collaboration style","Leadership upside","Community fit"]'::jsonb,
    12,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_coachability_feedback',
    'coachability_feedback',
    'If a reviewer or chapter lead gave you direct feedback that your lesson plan needed major changes, how would you respond?',
    'Tests coachability, humility, and growth mindset.',
    'What kind of feedback is hardest for you to receive, and how do you handle it?',
    'Coachability / Professionalism',
    'Coachability',
    'YPP can support developing instructors, but they need to be open to feedback and revision.',
    'Listen for openness without passivity. Strong candidates ask clarifying questions and improve the work.',
    'Receives feedback calmly, asks useful questions, revises concretely, and keeps student needs first.',
    '["Tell me about a time you changed your work after feedback.","How would you decide which feedback to act on first?","What support would help you revise well?"]'::jsonb,
    '["Shows humility and agency","Can describe revising based on feedback","Keeps the shared goal in view"]'::jsonb,
    '["Becomes defensive","Treats feedback as personal rejection","Says they accept feedback but cannot name a revision example"]'::jsonb,
    '["Initial reaction","Clarifying questions","Revision behavior","Growth mindset"]'::jsonb,
    13,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'iqb_candidate_questions',
    'candidate_questions',
    'What questions do you have for us about teaching with YPP, student support, curriculum expectations, or the chapter community?',
    'Tests preparation, seriousness, and what the candidate is paying attention to.',
    'What would you want to understand before committing to teach?',
    'Candidate Questions',
    'Preparation and mutual fit',
    'The questions candidates ask often reveal their maturity, priorities, and readiness to commit.',
    'Make room for their questions. Strong questions usually focus on students, expectations, support, and success criteria.',
    'Thoughtful questions about students, logistics, training, communication, and how to do the role well.',
    '["Is there anything about the role that feels unclear?","What support would help you be successful?","What concerns, if any, would you want to talk through before committing?"]'::jsonb,
    '["Asks thoughtful role-specific questions","Shows concern for doing the job well","Clarifies expectations before committing"]'::jsonb,
    '["No questions despite unclear commitment","Only asks about prestige or title","Questions reveal misunderstanding of the role"]'::jsonb,
    '["Questions asked","Preparedness","Concerns raised","Support needs"]'::jsonb,
    14,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("slug") DO UPDATE SET
  "prompt" = EXCLUDED."prompt",
  "helperText" = EXCLUDED."helperText",
  "followUpPrompt" = EXCLUDED."followUpPrompt",
  "topic" = EXCLUDED."topic",
  "competency" = EXCLUDED."competency",
  "whyItMatters" = EXCLUDED."whyItMatters",
  "interviewerGuidance" = EXCLUDED."interviewerGuidance",
  "listenFor" = EXCLUDED."listenFor",
  "suggestedFollowUps" = EXCLUDED."suggestedFollowUps",
  "strongSignals" = EXCLUDED."strongSignals",
  "concernSignals" = EXCLUDED."concernSignals",
  "notePrompts" = EXCLUDED."notePrompts",
  "sortOrder" = EXCLUDED."sortOrder",
  "isActive" = EXCLUDED."isActive",
  "updatedAt" = CURRENT_TIMESTAMP;
