"use server";
import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/prisma";
import { requireSessionUser, requireOfficer } from "@/lib/authorization";
import { requireStudentPortalUser } from "@/lib/family-access";

export async function saveStudentProfile(formData: FormData){ const user=await requireStudentPortalUser(); const interests=String(formData.get("interests")??"").split(",").map(s=>s.trim()).filter(Boolean); const goals=String(formData.get("goals")??"").trim(); await (prisma as any).profile.upsert({ where:{userId:user.id}, create:{userId:user.id, interests, primaryGoal:goals}, update:{interests, primaryGoal:goals} }); revalidatePath("/student/profile"); }
export async function submitAttendanceIssue(formData: FormData){ const user=await requireStudentPortalUser(); const sessionId=String(formData.get("sessionId")??""); const details=String(formData.get("details")??"").slice(0,1000); if(!sessionId||!details) return; const session=await prisma.classSession.findFirst({where:{id:sessionId, offering:{enrollments:{some:{studentId:user.id}}}}}); if(!session) throw new Error("Unauthorized"); await (prisma as any).familySupportRequest.create({data:{studentUserId:user.id, requesterUserId:user.id, category:"ATTENDANCE", subject:"Attendance review request", description:details, status:"OPEN", sessionId}}).catch(async()=>{}); revalidatePath("/student/attendance"); }
export async function expressRecommendationInterest(formData: FormData){ const user=await requireSessionUser(); const offeringId=String(formData.get("offeringId")??""); if(!offeringId) return; await (prisma as any).studentInterest.create({data:{userId:user.id, interestType:"CLASS", interestId:offeringId, notes:"Expressed interest from Session 8 recommendations"}}).catch(()=>null); revalidatePath("/student/recommendations"); }
export async function confirmInstructorAvailability(formData: FormData){ const user=await requireSessionUser(); const note=String(formData.get("note")??"").slice(0,1000); await (prisma as any).instructorGrowthEvent.create({data:{userId:user.id, type:"AVAILABILITY_UPDATED", summary:"Instructor availability updated", details:note}}).catch(()=>null); revalidatePath("/instructor/availability"); }
export async function confirmSessionReady(formData: FormData){ const user=await requireSessionUser(); const sessionId=String(formData.get("sessionId")??""); const note=String(formData.get("note")??"").slice(0,1000); const session=await prisma.classSession.findFirst({where:{id:sessionId, offering:{instructorId:user.id}}}); if(!session) throw new Error("Unauthorized"); await prisma.instructorSessionPreparation.upsert({where:{sessionId_instructorId:{sessionId,instructorId:user.id}}, create:{sessionId,instructorId:user.id, lessonReviewedAt:new Date(), materialsReviewedAt:new Date(), studentContextReviewedAt:new Date(), completedAt:new Date(), note}, update:{lessonReviewedAt:new Date(), materialsReviewedAt:new Date(), studentContextReviewedAt:new Date(), completedAt:new Date(), note}}); revalidatePath(`/instructor/classes/${session.offeringId}`); }
export async function createOperationalAction(formData: FormData){ const user=await requireOfficer(); const title=String(formData.get("title")??"").slice(0,200); if(!title) return; await (prisma as any).actionItem.create({data:{title, description:String(formData.get("description")??""), ownerId:String(formData.get("ownerId")??user.id), createdById:user.id, status:"OPEN", priority:String(formData.get("priority")??"MEDIUM")}}).catch(()=>null); revalidatePath("/chapter/weekly-plan"); revalidatePath("/chapter/workload"); }
export async function updateLaunchDecision(formData: FormData){ await requireOfficer(); const offeringId=String(formData.get("offeringId")??""); const summary=String(formData.get("summary")??"Launch decision updated"); if(!offeringId) return; await prisma.classOfferingTimelineEvent.create({data:{offeringId, kind:"NOTE", summary, payload:{session8:true}} as any}); revalidatePath(`/chapter/classes/${offeringId}/launch`); }
