import { prisma } from "@/lib/prisma";
import { requireSessionUser, requireOfficer } from "@/lib/authorization";
const includeOffering = { template:true, chapter:{select:{id:true,name:true}}, partner:{select:{id:true,name:true}}, sessions:{orderBy:[{date:"asc" as const},{startTime:"asc" as const}]}, enrollments:{include:{student:{select:{id:true,name:true,email:true,profile:true}}, attendance:true}}, announcements:{orderBy:{createdAt:"desc" as const}, take:5}, outcome:true };
export async function getInstructorHome(){ const user=await requireSessionUser(); const classes=await prisma.classOffering.findMany({where:{instructorId:user.id}, include:includeOffering, orderBy:{startDate:"desc"}, take:20}); const preparations=await prisma.instructorSessionPreparation.findMany({where:{instructorId:user.id}, include:{session:{include:{offering:{select:{id:true,title:true}}}}}, orderBy:{updatedAt:"desc"}, take:20}); return {user, classes, preparations}; }
export async function getInstructorClass(id:string){ const user=await requireSessionUser(); return prisma.classOffering.findFirst({where:{id, OR:[{instructorId:user.id},{regularInstructorAssignments:{some:{instructorId:user.id}}}]}, include:includeOffering}); }
export async function getInstructorSession(id:string, sessionId:string){ const user=await requireSessionUser(); return prisma.classSession.findFirst({where:{id:sessionId, offering:{id, OR:[{instructorId:user.id},{regularInstructorAssignments:{some:{instructorId:user.id}}}]}}, include:{offering:{include:includeOffering}, attendance:{include:{student:{select:{id:true,name:true,profile:true}}}}, preparations:{where:{instructorId:user.id}}, reflection:true}}); }
export async function getInstructorDevelopment(){ const user=await requireSessionUser(); const [growth, certs]=await Promise.all([(prisma as any).instructorGrowthEvent.findMany({where:{userId:user.id}, orderBy:{createdAt:"desc"}, take:20}).catch(()=>[]), (prisma as any).instructorCertification.findMany({where:{userId:user.id}, orderBy:{createdAt:"desc"}, take:20}).catch(()=>[])]); return {user,growth,certs}; }
export async function getOpsPipeline(){ await requireOfficer(); const [apps, instructors, needs]=await Promise.all([prisma.instructorApplication.findMany({orderBy:{updatedAt:"desc"}, take:50}).catch(()=>[]), prisma.user.findMany({where:{roles:{some:{role:"INSTRUCTOR" as any}}}, select:{id:true,name:true,email:true,createdAt:true}, take:50}).catch(()=>[]), prisma.classOffering.findMany({where:{status:{in:["DRAFT","PUBLISHED"] as any}}, include:{chapter:true, template:true, enrollments:true}, take:30}).catch(()=>[])]); return {apps,instructors,needs}; }
export async function getChapterOps(){ await requireOfficer(); const [classes, partners, actions, goals]=await Promise.all([prisma.classOffering.findMany({include:{template:true, chapter:true, partner:true, instructor:{select:{name:true}}, enrollments:true, sessions:true}, orderBy:{startDate:"desc"}, take:40}), prisma.partner.findMany({include:{contacts:true, requests:true, agreements:true, pipelineNotes:{orderBy:{createdAt:"desc"}, take:5}, classOfferings:true}, take:40}), (prisma as any).actionItem.findMany({where:{status:{notIn:["DONE","COMPLETED","CANCELLED"]}}, orderBy:{createdAt:"desc"}, take:80}).catch(()=>[]), (prisma as any).chapterGoal.findMany({orderBy:{createdAt:"desc"}, take:30}).catch(()=>[])]); return {classes,partners,actions,goals}; }
