-- Migration: final_review_tables
-- Phases 7 + 8 of the Final Review Cockpit redesign (plan §15 + §16).
--
-- Ships:
--   * `conditions Json?` column on InstructorApplicationChairDecision
--     (Phase 8 §16, APPROVE_WITH_CONDITIONS payload).
--   * `InstructorApplicationChairDraft` table — server-side persistence
--     for the cockpit's autosave rationale (Phase 8 §16, replaces the
--     localStorage-only stub from Phase 2B).
--   * `ChairDecisionCommitAttempt` table — server-enforced idempotency
--     keyed on the client UUID generated by `useCommitDecision`
--     (Phase 8 §16, replaces the best-effort retry guard).
--   * `ReviewSignal` + `ReviewSignalMention` tables — the unified
--     comment/note/highlight + threading + @mention abstraction from
--     Phase 7 §15 of the redesign plan.
--
-- All statements are guarded with IF NOT EXISTS / IF EXISTS / DO $$ BEGIN
-- ... EXCEPTION WHEN duplicate_object THEN null; END $$ so the migration
-- is safe to re-run against a partial state.

-- ============================================================
-- 1. Conditions column on chair decisions (Phase 8)
-- ============================================================

ALTER TABLE "InstructorApplicationChairDecision"
  ADD COLUMN IF NOT EXISTS "conditions" JSONB;

-- ============================================================
-- 2. Chair drafts — autosaved rationale per (application, chair)
-- ============================================================

CREATE TABLE IF NOT EXISTS "InstructorApplicationChairDraft" (
  "id"               TEXT        NOT NULL,
  "applicationId"    TEXT        NOT NULL,
  "chairId"          TEXT        NOT NULL,
  "rationale"        TEXT        NOT NULL DEFAULT '',
  "comparisonNotes"  TEXT        NOT NULL DEFAULT '',
  "savedAt"          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "InstructorApplicationChairDraft_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "InstructorApplicationChairDraft_applicationId_chairId_key"
  ON "InstructorApplicationChairDraft"("applicationId", "chairId");

CREATE INDEX IF NOT EXISTS "InstructorApplicationChairDraft_chairId_idx"
  ON "InstructorApplicationChairDraft"("chairId");

DO $$ BEGIN
  ALTER TABLE "InstructorApplicationChairDraft"
    ADD CONSTRAINT "InstructorApplicationChairDraft_applicationId_fkey"
    FOREIGN KEY ("applicationId")
    REFERENCES "InstructorApplication"("id")
    ON DELETE CASCADE
    ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "InstructorApplicationChairDraft"
    ADD CONSTRAINT "InstructorApplicationChairDraft_chairId_fkey"
    FOREIGN KEY ("chairId")
    REFERENCES "User"("id")
    ON DELETE CASCADE
    ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- ============================================================
-- 3. Commit attempts — server-enforced chairDecide() idempotency
-- ============================================================

CREATE TABLE IF NOT EXISTS "ChairDecisionCommitAttempt" (
  "id"              TEXT                  NOT NULL,
  "idempotencyKey"  TEXT                  NOT NULL,
  "applicationId"   TEXT                  NOT NULL,
  "chairId"         TEXT                  NOT NULL,
  "action"          "ChairDecisionAction" NOT NULL,
  "result"          TEXT                  NOT NULL,
  "decidedAt"       TIMESTAMP(3),
  "errorCode"       TEXT,
  "errorMessage"    TEXT,
  "createdAt"       TIMESTAMP(3)          NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"       TIMESTAMP(3)          NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "ChairDecisionCommitAttempt_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "ChairDecisionCommitAttempt_idempotencyKey_key"
  ON "ChairDecisionCommitAttempt"("idempotencyKey");

CREATE INDEX IF NOT EXISTS "ChairDecisionCommitAttempt_applicationId_createdAt_idx"
  ON "ChairDecisionCommitAttempt"("applicationId", "createdAt");

CREATE INDEX IF NOT EXISTS "ChairDecisionCommitAttempt_chairId_createdAt_idx"
  ON "ChairDecisionCommitAttempt"("chairId", "createdAt");

DO $$ BEGIN
  ALTER TABLE "ChairDecisionCommitAttempt"
    ADD CONSTRAINT "ChairDecisionCommitAttempt_applicationId_fkey"
    FOREIGN KEY ("applicationId")
    REFERENCES "InstructorApplication"("id")
    ON DELETE CASCADE
    ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "ChairDecisionCommitAttempt"
    ADD CONSTRAINT "ChairDecisionCommitAttempt_chairId_fkey"
    FOREIGN KEY ("chairId")
    REFERENCES "User"("id")
    ON DELETE CASCADE
    ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- ============================================================
-- 4. ReviewSignal — unified feedback abstraction (§15)
-- ============================================================

CREATE TABLE IF NOT EXISTS "ReviewSignal" (
  "id"             TEXT                     NOT NULL,
  "applicationId"  TEXT                     NOT NULL,
  "authorId"       TEXT                     NOT NULL,
  "kind"           "ReviewSignalKind"       NOT NULL DEFAULT 'COMMENT',
  "sentiment"      "ReviewSignalSentiment",
  "body"           TEXT                     NOT NULL,
  "pinned"         BOOLEAN                  NOT NULL DEFAULT FALSE,
  "pinnedAt"       TIMESTAMP(3),
  "pinnedById"     TEXT,
  "parentId"       TEXT,
  "resolvedAt"     TIMESTAMP(3),
  "resolvedById"   TEXT,
  "createdAt"      TIMESTAMP(3)             NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"      TIMESTAMP(3)             NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "ReviewSignal_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "ReviewSignal_applicationId_createdAt_idx"
  ON "ReviewSignal"("applicationId", "createdAt");

CREATE INDEX IF NOT EXISTS "ReviewSignal_applicationId_pinned_idx"
  ON "ReviewSignal"("applicationId", "pinned");

CREATE INDEX IF NOT EXISTS "ReviewSignal_authorId_idx"
  ON "ReviewSignal"("authorId");

CREATE INDEX IF NOT EXISTS "ReviewSignal_parentId_idx"
  ON "ReviewSignal"("parentId");

DO $$ BEGIN
  ALTER TABLE "ReviewSignal"
    ADD CONSTRAINT "ReviewSignal_applicationId_fkey"
    FOREIGN KEY ("applicationId")
    REFERENCES "InstructorApplication"("id")
    ON DELETE CASCADE
    ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "ReviewSignal"
    ADD CONSTRAINT "ReviewSignal_authorId_fkey"
    FOREIGN KEY ("authorId")
    REFERENCES "User"("id")
    ON DELETE CASCADE
    ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "ReviewSignal"
    ADD CONSTRAINT "ReviewSignal_pinnedById_fkey"
    FOREIGN KEY ("pinnedById")
    REFERENCES "User"("id")
    ON DELETE SET NULL
    ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "ReviewSignal"
    ADD CONSTRAINT "ReviewSignal_resolvedById_fkey"
    FOREIGN KEY ("resolvedById")
    REFERENCES "User"("id")
    ON DELETE SET NULL
    ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "ReviewSignal"
    ADD CONSTRAINT "ReviewSignal_parentId_fkey"
    FOREIGN KEY ("parentId")
    REFERENCES "ReviewSignal"("id")
    ON DELETE CASCADE
    ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- ============================================================
-- 5. ReviewSignalMention — @mention edges (§15)
-- ============================================================

CREATE TABLE IF NOT EXISTS "ReviewSignalMention" (
  "signalId"       TEXT          NOT NULL,
  "userId"         TEXT          NOT NULL,
  "createdAt"      TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "acknowledgedAt" TIMESTAMP(3),

  CONSTRAINT "ReviewSignalMention_pkey" PRIMARY KEY ("signalId", "userId")
);

CREATE INDEX IF NOT EXISTS "ReviewSignalMention_userId_acknowledgedAt_idx"
  ON "ReviewSignalMention"("userId", "acknowledgedAt");

DO $$ BEGIN
  ALTER TABLE "ReviewSignalMention"
    ADD CONSTRAINT "ReviewSignalMention_signalId_fkey"
    FOREIGN KEY ("signalId")
    REFERENCES "ReviewSignal"("id")
    ON DELETE CASCADE
    ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE "ReviewSignalMention"
    ADD CONSTRAINT "ReviewSignalMention_userId_fkey"
    FOREIGN KEY ("userId")
    REFERENCES "User"("id")
    ON DELETE CASCADE
    ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null;
END $$;
