import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { redirect } from "next/navigation";
import Link from "next/link";
import { prisma } from "@/lib/prisma";

export default async function ParentReportsPage() {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) redirect("/login");

  const roles = session.user.roles ?? [];
  if (!roles.includes("PARENT") && !roles.includes("ADMIN")) redirect("/");

  const userId = session.user.id;

  // Get linked students (approved only)
  const links = await prisma.parentStudent.findMany({
    where: { parentId: userId, approvalStatus: "APPROVED" },
    select: { studentId: true, student: { select: { name: true } } },
  });

  const studentIds = links.map((l) => l.studentId);
  const studentNameMap = new Map(links.map((l) => [l.studentId, l.student.name]));

  // Fetch progress reports for linked students
  const reports = studentIds.length > 0
    ? await prisma.progressReport.findMany({
        where: {
          studentId: { in: studentIds },
          sentToParents: true,
        },
        include: {
          student: { select: { id: true, name: true } },
        },
        orderBy: { generatedAt: "desc" },
        take: 20,
      })
    : [];

  // Group reports by student
  const reportsByStudent = new Map<string, typeof reports>();
  for (const r of reports) {
    const existing = reportsByStudent.get(r.studentId) ?? [];
    existing.push(r);
    reportsByStudent.set(r.studentId, existing);
  }

  return (
    <div>
      <div className="topbar">
        <div>
          <Link href="/parent" style={{ fontSize: 13, color: "var(--muted)" }}>
            &larr; Parent Portal
          </Link>
          <h1 className="page-title">Progress Reports</h1>
          <p style={{ fontSize: 13, color: "var(--text-secondary)", marginTop: 2 }}>
            Detailed progress reports generated by instructors
          </p>
        </div>
      </div>

      {studentIds.length === 0 ? (
        <div className="card" style={{ textAlign: "center", padding: 40 }}>
          <h3>No linked students</h3>
          <p style={{ color: "var(--text-secondary)" }}>
            Link a student account to view their progress reports.
          </p>
          <Link href="/parent/connect" className="button primary" style={{ marginTop: 12 }}>
            Connect a Student
          </Link>
        </div>
      ) : reports.length === 0 ? (
        <div className="card" style={{ textAlign: "center", padding: 40 }}>
          <h3>No reports available yet</h3>
          <p style={{ color: "var(--text-secondary)" }}>
            Progress reports are generated periodically by instructors.
            You&apos;ll see them here once they&apos;re published.
          </p>
          <p style={{ fontSize: 12, color: "var(--muted)", marginTop: 8 }}>
            Linked students: {links.map((l) => l.student.name).join(", ")}
          </p>
        </div>
      ) : (
        <>
          {/* Stats */}
          <div className="grid two" style={{ marginBottom: 24 }}>
            <div className="card" style={{ textAlign: "center" }}>
              <div className="kpi">{reports.length}</div>
              <div className="kpi-label">Total Reports</div>
            </div>
            <div className="card" style={{ textAlign: "center" }}>
              <div className="kpi">{reportsByStudent.size}</div>
              <div className="kpi-label">Students with Reports</div>
            </div>
          </div>

          {/* Reports by Student */}
          {Array.from(reportsByStudent.entries()).map(([studentId, studentReports]) => (
            <div key={studentId} style={{ marginBottom: 28 }}>
              <div className="section-title">
                {studentNameMap.get(studentId) ?? "Student"}
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
                {studentReports.map((report) => (
                  <div key={report.id} className="card">
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "start", marginBottom: 12 }}>
                      <div>
                        <span className="pill" style={{ marginRight: 8 }}>
                          {report.reportType}
                        </span>
                        <span style={{ fontSize: 13, color: "var(--muted)" }}>
                          {new Date(report.periodStart).toLocaleDateString()} &ndash;{" "}
                          {new Date(report.periodEnd).toLocaleDateString()}
                        </span>
                      </div>
                      <span style={{ fontSize: 11, color: "var(--muted)" }}>
                        Generated {new Date(report.generatedAt).toLocaleDateString()}
                      </span>
                    </div>

                    {/* Summary Stats */}
                    <div className="grid four" style={{ marginBottom: 16 }}>
                      <div style={{ textAlign: "center" }}>
                        <div style={{ fontSize: 20, fontWeight: 700 }}>{report.totalXPEarned}</div>
                        <div style={{ fontSize: 11, color: "var(--muted)" }}>XP Earned</div>
                      </div>
                      <div style={{ textAlign: "center" }}>
                        <div style={{ fontSize: 20, fontWeight: 700 }}>{report.passionsActive}</div>
                        <div style={{ fontSize: 11, color: "var(--muted)" }}>Active Passions</div>
                      </div>
                      <div style={{ textAlign: "center" }}>
                        <div style={{ fontSize: 20, fontWeight: 700 }}>{report.hoursLogged}</div>
                        <div style={{ fontSize: 11, color: "var(--muted)" }}>Hours Logged</div>
                      </div>
                      <div style={{ textAlign: "center" }}>
                        <div style={{ fontSize: 20, fontWeight: 700 }}>{report.projectsCompleted}</div>
                        <div style={{ fontSize: 11, color: "var(--muted)" }}>Projects Done</div>
                      </div>
                    </div>

                    {/* Narrative sections */}
                    {report.highlights && (
                      <div style={{ marginBottom: 12 }}>
                        <div style={{ fontWeight: 600, fontSize: 13, marginBottom: 4, color: "#16a34a" }}>
                          Highlights
                        </div>
                        <p style={{ margin: 0, fontSize: 13 }}>{report.highlights}</p>
                      </div>
                    )}

                    {report.areasOfGrowth && (
                      <div style={{ marginBottom: 12 }}>
                        <div style={{ fontWeight: 600, fontSize: 13, marginBottom: 4, color: "#d97706" }}>
                          Areas of Growth
                        </div>
                        <p style={{ margin: 0, fontSize: 13 }}>{report.areasOfGrowth}</p>
                      </div>
                    )}

                    {report.recommendations && (
                      <div style={{ marginBottom: 12 }}>
                        <div style={{ fontWeight: 600, fontSize: 13, marginBottom: 4, color: "#3b82f6" }}>
                          Recommendations
                        </div>
                        <p style={{ margin: 0, fontSize: 13 }}>{report.recommendations}</p>
                      </div>
                    )}

                    {report.instructorNotes && (
                      <div
                        style={{
                          padding: 12,
                          background: "var(--surface-alt)",
                          borderRadius: "var(--radius-sm)",
                          borderLeft: "3px solid var(--ypp-purple)",
                        }}
                      >
                        <div style={{ fontWeight: 600, fontSize: 12, marginBottom: 4 }}>
                          Instructor Notes
                        </div>
                        <p style={{ margin: 0, fontSize: 13, color: "var(--text-secondary)" }}>
                          {report.instructorNotes}
                        </p>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </>
      )}
    </div>
  );
}
