import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { redirect } from "next/navigation";
import EmptyState from "@/components/empty-state";

export default async function ParentReportsPage() {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    redirect("/login");
  }

  return (
    <EmptyState
      icon="📝"
      badge="Parent Portal"
      title="Progress Reports"
      description="This page will display detailed monthly progress reports generated by instructors — including achievements, areas of growth, instructor observations, and recommendations."
      addedBy="instructors (reports are generated monthly)"
      actionLabel="Connect a Student"
      actionHref="/parent/connect"
    />
  );
}
